import type { MovementPattern } from "../types";

export const MOVEMENT_PATTERNS = [
  {
    id: "squat",
    label: "Squat",
    group: "lower-body-compound",
    description: "Knee-dominant lower-body lowering and standing pattern.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "abs"],
    aliases: ["knee dominant", "sit to stand"],
    fatigueTags: ["knee-extension", "axial-load"],
  },
  {
    id: "hinge",
    label: "Hinge",
    group: "lower-body-compound",
    description: "Hip-dominant flexion and extension pattern.",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["lower-back", "abs"],
    aliases: ["deadlift", "hip hinge", "posterior chain"],
    fatigueTags: ["hip-extension", "posterior-chain"],
  },
  {
    id: "lunge",
    label: "Lunge",
    group: "lower-body-compound",
    description: "Split-stance lower-body loading.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors", "abs"],
    aliases: ["split stance", "single leg"],
    fatigueTags: ["unilateral-leg", "knee-extension"],
  },
  {
    id: "step-up",
    label: "Step-Up",
    group: "lower-body-compound",
    description: "Vertical stepping movement onto or down from elevation.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["calves", "abs"],
    aliases: ["step down", "box step"],
    fatigueTags: ["unilateral-leg", "gait"],
  },
  {
    id: "hip-thrust-bridge",
    label: "Hip Thrust / Bridge",
    group: "lower-body-compound",
    description: "Horizontal hip extension with reduced spinal demand.",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "abs"],
    aliases: ["glute bridge", "hip thrust"],
    fatigueTags: ["hip-extension", "glutes"],
  },
  {
    id: "knee-extension",
    label: "Knee Extension",
    group: "lower-body-isolation",
    description: "Knee extension isolation movement.",
    primaryMuscles: ["quads"],
    aliases: ["leg extension", "terminal knee extension"],
    fatigueTags: ["quads"],
  },
  {
    id: "knee-flexion",
    label: "Knee Flexion",
    group: "lower-body-isolation",
    description: "Hamstring knee-flexion isolation movement.",
    primaryMuscles: ["hamstrings"],
    aliases: ["leg curl", "hamstring curl", "nordic curl"],
    fatigueTags: ["hamstrings"],
  },
  {
    id: "hip-abduction",
    label: "Hip Abduction",
    group: "lower-body-isolation",
    description: "Moving the leg away from midline.",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["adductors"],
    aliases: ["band walk", "clamshell"],
    fatigueTags: ["lateral-hip"],
  },
  {
    id: "hip-adduction",
    label: "Hip Adduction",
    group: "lower-body-isolation",
    description: "Moving the leg toward midline.",
    primaryMuscles: ["adductors"],
    aliases: ["adductor machine", "copenhagen plank"],
    fatigueTags: ["adductors"],
  },
  {
    id: "hip-internal-rotation",
    label: "Hip Internal Rotation",
    group: "lower-body-isolation",
    description: "Rotating the femur inward through the hip.",
    primaryMuscles: ["glutes", "hip-flexors"],
    aliases: ["hip ir", "internal hip rotation"],
    fatigueTags: ["hip-rotation", "rotator-control"],
  },
  {
    id: "hip-external-rotation",
    label: "Hip External Rotation",
    group: "lower-body-isolation",
    description: "Rotating the femur outward through the hip.",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["adductors"],
    aliases: ["hip er", "external hip rotation", "clamshell"],
    fatigueTags: ["hip-rotation", "lateral-hip"],
  },
  {
    id: "calf-raise",
    label: "Calf Raise",
    group: "lower-body-isolation",
    description: "Plantar flexion through the ankle.",
    primaryMuscles: ["calves"],
    aliases: ["plantar flexion"],
    fatigueTags: ["calves"],
  },
  {
    id: "tibialis-raise",
    label: "Tibialis Raise",
    group: "lower-body-isolation",
    description: "Dorsiflexion-focused ankle isolation.",
    primaryMuscles: ["tibialis-anterior"],
    secondaryMuscles: ["calves"],
    aliases: ["ankle dorsiflexion", "toe raise", "shin raise"],
    fatigueTags: ["ankle-dorsiflexion", "lower-leg"],
  },
  {
    id: "chest-press",
    label: "Chest Press",
    group: "upper-push",
    description: "Pressing away from the torso with chest emphasis.",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    aliases: ["push up", "push-up", "bench press", "horizontal press"],
    fatigueTags: ["horizontal-push", "pressing"],
  },
  {
    id: "shoulder-press",
    label: "Shoulder Press",
    group: "upper-push",
    description: "Pressing overhead or upward.",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "abs"],
    aliases: ["overhead press", "vertical press"],
    fatigueTags: ["vertical-push", "pressing"],
  },
  {
    id: "chest-fly",
    label: "Chest Fly",
    group: "upper-push",
    description: "Shoulder horizontal adduction with chest emphasis.",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    aliases: ["pec fly", "cable fly"],
    fatigueTags: ["chest", "shoulder-adduction"],
  },
  {
    id: "lateral-raise",
    label: "Lateral Raise",
    group: "upper-push",
    description: "Shoulder abduction isolation for lateral delts.",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    aliases: ["side raise", "shoulder abduction"],
    fatigueTags: ["shoulder-abduction", "delts"],
  },
  {
    id: "row",
    label: "Row",
    group: "upper-pull",
    description: "Pulling toward the torso.",
    primaryMuscles: ["upper-back", "lats"],
    secondaryMuscles: ["biceps", "rear-delts"],
    aliases: ["horizontal pull"],
    fatigueTags: ["horizontal-pull", "scapular-retraction"],
  },
  {
    id: "vertical-pull",
    label: "Vertical Pull",
    group: "upper-pull",
    description: "Pulling down or pulling the body upward.",
    primaryMuscles: ["lats", "upper-back"],
    secondaryMuscles: ["biceps", "abs"],
    aliases: ["pull up", "chin up", "pulldown"],
    fatigueTags: ["vertical-pull", "lats"],
  },
  {
    id: "pullover",
    label: "Pullover",
    group: "upper-pull",
    description: "Shoulder extension pattern with lat emphasis.",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["chest", "triceps"],
    aliases: ["straight arm pulldown"],
    fatigueTags: ["lats", "shoulder-extension"],
  },
  {
    id: "reverse-fly",
    label: "Reverse Fly",
    group: "upper-pull",
    description: "Shoulder horizontal abduction with rear-delt and upper-back emphasis.",
    primaryMuscles: ["rear-delts", "upper-back"],
    secondaryMuscles: ["rotator-cuff", "traps"],
    aliases: ["rear delt fly", "rear delt raise"],
    fatigueTags: ["rear-delts", "scapular-control"],
  },
  {
    id: "curl",
    label: "Curl",
    group: "arm-isolation",
    description: "Elbow flexion for biceps and arm strength.",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    aliases: ["biceps curl"],
    fatigueTags: ["elbow-flexion"],
  },
  {
    id: "triceps-extension",
    label: "Triceps Extension",
    group: "arm-isolation",
    description: "Elbow extension for triceps strength.",
    primaryMuscles: ["triceps"],
    aliases: ["pushdown", "skullcrusher"],
    fatigueTags: ["elbow-extension"],
  },
  {
    id: "wrist-flexion",
    label: "Wrist Flexion",
    group: "arm-isolation",
    description: "Flexing the wrist against resistance.",
    primaryMuscles: ["forearms"],
    fatigueTags: ["forearms"],
  },
  {
    id: "wrist-extension",
    label: "Wrist Extension",
    group: "arm-isolation",
    description: "Extending the wrist against resistance.",
    primaryMuscles: ["forearms"],
    fatigueTags: ["forearms"],
  },
  {
    id: "wrist-rotation",
    label: "Wrist Rotation",
    group: "arm-isolation",
    description: "Pronation, supination, and deviation control of the wrist/forearm.",
    primaryMuscles: ["forearms"],
    fatigueTags: ["forearms", "rotation"],
  },
  {
    id: "shoulder-internal-rotation",
    label: "Shoulder Internal Rotation",
    group: "arm-isolation",
    description: "Rotator-cuff internal rotation pattern.",
    primaryMuscles: ["rotator-cuff"],
    secondaryMuscles: ["shoulders"],
    aliases: ["shoulder ir", "internal rotation"],
    fatigueTags: ["rotator-cuff", "shoulder-rotation"],
  },
  {
    id: "shoulder-external-rotation",
    label: "Shoulder External Rotation",
    group: "arm-isolation",
    description: "Rotator-cuff external rotation pattern.",
    primaryMuscles: ["rotator-cuff"],
    secondaryMuscles: ["rear-delts", "shoulders"],
    aliases: ["shoulder er", "external rotation"],
    fatigueTags: ["rotator-cuff", "shoulder-rotation"],
  },
  {
    id: "scapular-control",
    label: "Scapular Control",
    group: "arm-isolation",
    description: "Scapular retraction, protraction, elevation, depression, or control drill.",
    primaryMuscles: ["upper-back", "traps"],
    secondaryMuscles: ["rotator-cuff", "rear-delts"],
    aliases: ["scapular retraction", "scapular protraction", "face pull"],
    fatigueTags: ["scapular-control", "upper-back"],
  },
  {
    id: "rotation",
    label: "Rotation",
    group: "core",
    description: "Producing rotational force through the trunk and hips.",
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["glutes"],
    fatigueTags: ["rotation", "core"],
  },
  {
    id: "anti-rotation",
    label: "Anti-Rotation",
    group: "core",
    description: "Resisting rotational force through the trunk.",
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: ["glutes"],
    aliases: ["resist rotation"],
    fatigueTags: ["anti-rotation", "core"],
  },
  {
    id: "flexion",
    label: "Flexion",
    group: "core",
    description: "Trunk flexion or spinal flexion control.",
    primaryMuscles: ["abs"],
    fatigueTags: ["core-flexion"],
  },
  {
    id: "anti-extension",
    label: "Anti-Extension",
    group: "core",
    description: "Resisting spinal extension.",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["lats", "shoulders"],
    fatigueTags: ["anti-extension", "core"],
  },
  {
    id: "anti-lateral-flexion",
    label: "Anti-Lateral Flexion",
    group: "core",
    description: "Resisting side bending.",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["grip", "traps"],
    fatigueTags: ["anti-lateral-flexion", "carry"],
  },
  {
    id: "carry",
    label: "Carry",
    group: "athletic",
    description: "Loaded locomotion pattern.",
    primaryMuscles: ["grip", "traps", "abs"],
    secondaryMuscles: ["glutes"],
    fatigueTags: ["carry", "gait"],
  },
  {
    id: "crawl",
    label: "Crawl",
    group: "athletic",
    description: "Ground-based quadruped locomotion and coordination.",
    primaryMuscles: ["abs", "shoulders"],
    secondaryMuscles: ["quads", "glutes"],
    fatigueTags: ["crawl", "conditioning"],
  },
  {
    id: "jump",
    label: "Jump",
    group: "athletic",
    description: "Explosive takeoff and landing pattern.",
    primaryMuscles: ["quads", "glutes", "calves"],
    fatigueTags: ["plyometric", "power"],
  },
  {
    id: "sprint",
    label: "Sprint",
    group: "athletic",
    description: "Rapid locomotion, acceleration, or max velocity pattern.",
    primaryMuscles: ["glutes", "hamstrings", "calves"],
    fatigueTags: ["sprint", "conditioning"],
  },
  {
    id: "throw",
    label: "Throw",
    group: "athletic",
    description: "Explosive force projection through an implement.",
    primaryMuscles: ["abs", "shoulders", "chest"],
    secondaryMuscles: ["glutes"],
    fatigueTags: ["throw", "power"],
  },
  {
    id: "mobility",
    label: "Mobility",
    group: "mobility",
    description: "Movement quality, range, and control drills.",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["glutes", "shoulders"],
    aliases: ["mobility drill", "range of motion"],
    fatigueTags: ["low-fatigue", "mobility"],
  },
  {
    id: "breathing-bracing",
    label: "Breathing / Bracing",
    group: "mobility",
    description: "Breathing mechanics, trunk pressure, and bracing coordination.",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques", "lower-back"],
    aliases: ["bracing", "breathing", "core brace"],
    fatigueTags: ["low-fatigue", "bracing", "core-control"],
  },
  {
    id: "neck-flexion",
    label: "Neck Flexion",
    group: "cervical-isolation",
    description: "Cervical flexion isolation and control.",
    primaryMuscles: ["neck"],
    aliases: ["cervical flexion"],
    fatigueTags: ["neck", "cervical"],
  },
  {
    id: "neck-extension",
    label: "Neck Extension",
    group: "cervical-isolation",
    description: "Cervical extension isolation and control.",
    primaryMuscles: ["neck"],
    aliases: ["cervical extension"],
    fatigueTags: ["neck", "cervical"],
  },
  {
    id: "neck-rotation",
    label: "Neck Rotation",
    group: "cervical-isolation",
    description: "Cervical rotation isolation and control.",
    primaryMuscles: ["neck"],
    aliases: ["cervical rotation"],
    fatigueTags: ["neck", "cervical-rotation"],
  },
  {
    id: "integrated-movement",
    label: "Integrated Movement",
    group: "integrated",
    description: "Multi-pattern exercise combining several movement demands.",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["glutes", "shoulders", "chest", "quads"],
    aliases: ["complex", "combo"],
    fatigueTags: ["multi-pattern", "conditioning"],
  },
] as const satisfies readonly MovementPattern[];

export const MOVEMENT_PATTERN_BY_ID = Object.fromEntries(
  MOVEMENT_PATTERNS.map((pattern) => [pattern.id, pattern]),
) as unknown as Record<MovementPattern["id"], MovementPattern>;
