import type {
  CoreMovementId,
  ExerciseCatalogItem,
  ExerciseModifierId,
  MovementPatternId,
} from "@/types";
import { getExerciseImage } from "./exerciseLibrary";

export type CoreMovementPatternCategory =
  | "Lower Body Compound"
  | "Lower Body Isolation"
  | "Upper Push"
  | "Upper Pull"
  | "Arm Isolation"
  | "Core"
  | "Athletic"
  | "Mobility"
  | "Cervical Isolation"
  | "Integrated";

export type CoreMovementPatternCardDefinition = {
  id: `core-${string}`;
  name: string;
  category: CoreMovementPatternCategory;
  coreMovementId: CoreMovementId;
  movementPatternId: MovementPatternId;
  description: string;
  body: string;
  muscles: string;
  goal: string;
  equipment: string;
  level: string;
  modifierIds: ExerciseModifierId[];
  aliases: string[];
  integrated?: boolean;
};

export const CORE_MOVEMENT_PATTERN_VARIATION_NAMES: Partial<
  Record<CoreMovementPatternCardDefinition["id"], readonly string[]>
> = {
  "core-chest-press": [
    "Push-Up",
    "Diamond Push-Up",
    "Incline Push-Up",
    "Decline Push-Up",
    "Bench Press",
    "Incline Dumbbell Press",
    "Floor Press",
    "Plyo Push-Up",
  ],
  "core-squat": [
    "Air Squat",
    "Goblet Squat",
    "Front Squat",
    "Back Squat",
    "Overhead Squat",
    "Sumo Squat",
    "Box Squat",
    "Hack Squat",
    "Zercher Squat",
    "Cossack Squat",
    "Jump Squat",
  ],
  "core-hinge": [
    "Conventional Deadlift",
    "Sumo Deadlift",
    "Romanian Deadlift",
    "Stiff Leg Deadlift",
    "Single Leg RDL",
    "Good Morning",
    "Trap Bar Deadlift",
    "Kettlebell Swing",
    "Snatch Grip Deadlift",
  ],
  "core-lunge": [
    "Reverse Lunge",
    "Forward Lunge",
    "Walking Lunge",
    "Curtsy Lunge",
    "Lateral Lunge",
    "Deficit Lunge",
    "Bulgarian Split Squat",
    "Lunge to Press",
    "Lunge to Curl",
  ],
  "core-step-up": [
    "Step-Up",
    "Lateral Step-Up",
    "Step-Up with Knee Drive",
    "Plyometric Step-Up",
  ],
  "core-hip-thrust-bridge": [
    "Glute Bridge",
    "Hip Thrust",
    "Single Leg Hip Thrust",
    "Frog Pump",
  ],
  "core-knee-extension": ["Leg Extension", "Terminal Knee Extension"],
  "core-knee-flexion": [
    "Seated Hamstring Curl",
    "Lying Hamstring Curl",
    "Nordic Curl",
    "Stability Ball Ham Curl",
  ],
  "core-hip-abduction": ["Band Walk", "Clamshell", "Hip Abduction Machine"],
  "core-hip-adduction": ["Adductor Machine", "Copenhagen Plank"],
  "core-calf-raise": [
    "Standing Calf Raise",
    "Seated Calf Raise",
    "Single Leg Calf Raise",
  ],
  "core-tibialis-raise": ["Wall Tibialis Raise", "Standing Tibialis Raise"],
  "core-shoulder-press": [
    "Dumbbell Shoulder Press",
    "Arnold Press",
    "Push Press",
    "Z Press",
    "Landmine Press",
  ],
  "core-chest-fly": ["Dumbbell Fly", "Cable Fly", "Pec Deck"],
  "core-lateral-raise": [
    "Dumbbell Lateral Raise",
    "Cable Lateral Raise",
    "Band Lateral Raise",
  ],
  "core-reverse-fly": [
    "Dumbbell Reverse Fly",
    "Cable Reverse Fly",
    "Band Reverse Fly",
    "Rear Delt Fly",
  ],
  "core-row": [
    "Bent Over Row",
    "Gorilla Row",
    "Seal Row",
    "Renegade Row",
    "Meadows Row",
  ],
  "core-vertical-pull": [
    "Pull-Up",
    "Chin-Up",
    "Neutral Grip Pull-Up",
    "Lat Pulldown",
  ],
  "core-pullover": ["Dumbbell Pullover", "Straight Arm Pulldown"],
  "core-curl": [
    "Hammer Curl",
    "Preacher Curl",
    "Incline Curl",
    "Concentration Curl",
  ],
  "core-triceps-extension": [
    "Skullcrusher",
    "Pushdown",
    "Overhead Extension",
    "Kickback",
  ],
  "core-wrist-flexion": ["Wrist Curl", "Behind Back Wrist Curl"],
  "core-wrist-extension": ["Reverse Wrist Curl"],
  "core-wrist-rotation": [
    "Hammer Rotation",
    "Club Rotation",
    "Band Pronation/Supination",
  ],
  "core-shoulder-internal-rotation": [
    "Band Shoulder Internal Rotation",
    "Cable Shoulder Internal Rotation",
  ],
  "core-shoulder-external-rotation": [
    "Band Shoulder External Rotation",
    "Cable Shoulder External Rotation",
    "Side-Lying External Rotation",
  ],
  "core-scapular-control": [
    "Scapular Push-Up",
    "Scapular Pull-Up",
    "Wall Slide",
    "Serratus Wall Slide",
  ],
  "core-rotation": [
    "Russian Twist",
    "Cable Woodchop",
    "Med Ball Rotational Throw",
    "Landmine Rotation",
  ],
  "core-anti-rotation": ["Pallof Press", "Renegade Hold", "Single Arm Carry"],
  "core-flexion": ["Crunch", "Sit-Up", "Reverse Crunch", "Hanging Leg Raise"],
  "core-anti-extension": ["Plank", "Ab Wheel Rollout", "Dead Bug", "Body Saw"],
  "core-anti-lateral-flexion": ["Side Plank", "Suitcase Carry", "Offset Hold"],
  "core-carry": [
    "Farmer Carry",
    "Suitcase Carry",
    "Front Rack Carry",
    "Overhead Carry",
    "Waiter Carry",
  ],
  "core-crawl": ["Bear Crawl", "Leopard Crawl", "Lateral Crawl"],
  "core-jump": ["Box Jump", "Broad Jump", "Depth Jump", "Single Leg Hop"],
  "core-sprint": ["Hill Sprint", "Sled Sprint", "Shuttle Sprint"],
  "core-throw": ["Med Ball Chest Pass", "Rotational Throw", "Slam Ball Slam"],
  "core-mobility": [
    "90/90 Hip Mobility",
    "Thoracic Rotation",
    "Couch Stretch",
    "World's Greatest Stretch",
  ],
  "core-breathing-bracing": [
    "90/90 Breathing",
    "Crocodile Breathing",
    "Dead Bug Breathing",
  ],
  "core-neck-flexion": ["Supine Neck Flexion"],
  "core-neck-extension": ["Prone Neck Extension"],
  "core-neck-rotation": ["Seated Neck Rotation"],
  "core-integrated-movement": [
    "Burpee",
    "Thruster",
    "Turkish Get-Up",
    "Man Maker",
    "Devil Press",
    "Clean to Press",
    "Lunge to Curl",
    "Lunge to Press",
  ],
};

export const getCoreMovementPatternVariationNames = (
  id: CoreMovementPatternCardDefinition["id"],
) => [...(CORE_MOVEMENT_PATTERN_VARIATION_NAMES[id] || [])];

export type CoreMovementSemanticVariation = {
  id: string;
  name: string;
  modifierIds: ExerciseModifierId[];
  matchModifierSets: ExerciseModifierId[][];
  aliases: string[];
};

const SEMANTIC_VARIATION_MODIFIER_IDS: Partial<
  Record<string, readonly ExerciseModifierId[]>
> = {
  "Push-Up": [
    "apparatus:bodyweight",
    "angle-position:floor",
    "limb-usage:standard-stance",
  ],
  "Diamond Push-Up": [
    "apparatus:bodyweight",
    "angle-position:floor",
    "limb-usage:close-grip",
  ],
  "Incline Push-Up": [
    "apparatus:bodyweight",
    "angle-position:hands-elevated",
    "limb-usage:standard-stance",
  ],
  "Decline Push-Up": [
    "apparatus:bodyweight",
    "angle-position:feet-elevated",
    "limb-usage:standard-stance",
  ],
  "Bench Press": ["apparatus:barbell", "angle-position:flat"],
  "Incline Dumbbell Press": ["apparatus:dumbbell", "angle-position:incline"],
  "Floor Press": [
    "apparatus:dumbbell",
    "angle-position:floor",
    "range-of-motion:dead-stop",
  ],
  "Plyo Push-Up": [
    "apparatus:bodyweight",
    "angle-position:floor",
    "tempo:explosive",
    "load-behavior:ballistic",
  ],
  "Air Squat": ["apparatus:bodyweight", "limb-usage:standard-stance"],
  "Goblet Squat": ["apparatus:kettlebell", "angle-position:goblet"],
  "Front Squat": ["apparatus:barbell", "angle-position:front-loaded"],
  "Back Squat": ["apparatus:barbell", "angle-position:back-loaded"],
  "Overhead Squat": ["apparatus:barbell", "angle-position:overhead"],
  "Sumo Squat": ["apparatus:bodyweight", "limb-usage:sumo-stance"],
  "Box Squat": ["apparatus:box", "angle-position:seated"],
  "Hack Squat": ["apparatus:machine"],
  "Zercher Squat": ["apparatus:barbell", "angle-position:front-loaded"],
  "Cossack Squat": ["apparatus:bodyweight", "limb-usage:wide-stance"],
  "Jump Squat": [
    "apparatus:bodyweight",
    "tempo:explosive",
    "load-behavior:ballistic",
  ],
  "Conventional Deadlift": [
    "apparatus:barbell",
    "limb-usage:conventional-stance",
    "range-of-motion:dead-stop",
  ],
  "Sumo Deadlift": [
    "apparatus:barbell",
    "limb-usage:sumo-stance",
    "range-of-motion:dead-stop",
  ],
  "Romanian Deadlift": ["tempo:slow-eccentric", "range-of-motion:full-rom"],
  "Stiff Leg Deadlift": ["tempo:slow-eccentric", "range-of-motion:full-rom"],
  "Single Leg RDL": [
    "limb-usage:single-leg",
    "tempo:slow-eccentric",
    "range-of-motion:full-rom",
  ],
  "Good Morning": ["apparatus:barbell", "angle-position:back-loaded"],
  "Trap Bar Deadlift": [
    "apparatus:trap-bar",
    "limb-usage:neutral-grip",
    "range-of-motion:dead-stop",
  ],
  "Kettlebell Swing": [
    "apparatus:kettlebell",
    "tempo:explosive",
    "load-behavior:ballistic",
  ],
  "Snatch Grip Deadlift": [
    "apparatus:barbell",
    "limb-usage:wide-grip",
    "range-of-motion:dead-stop",
  ],
  "Reverse Lunge": ["apparatus:bodyweight", "angle-position:split-stance"],
  "Forward Lunge": ["apparatus:bodyweight", "angle-position:split-stance"],
  "Walking Lunge": ["apparatus:bodyweight", "load-behavior:cyclical"],
  "Curtsy Lunge": ["apparatus:bodyweight", "angle-position:split-stance"],
  "Lateral Lunge": ["apparatus:bodyweight", "limb-usage:wide-stance"],
  "Deficit Lunge": ["apparatus:bodyweight", "range-of-motion:deficit"],
  "Bulgarian Split Squat": [
    "apparatus:bodyweight",
    "angle-position:rear-foot-elevated",
    "limb-usage:unilateral",
  ],
  "Lunge to Press": ["angle-position:split-stance", "load-behavior:skill-complex"],
  "Lunge to Curl": ["angle-position:split-stance", "load-behavior:skill-complex"],
  "Step-Up": ["apparatus:bodyweight", "apparatus:box"],
  "Lateral Step-Up": ["apparatus:box", "limb-usage:unilateral"],
  "Step-Up with Knee Drive": ["apparatus:box", "limb-usage:unilateral"],
  "Plyometric Step-Up": [
    "apparatus:box",
    "tempo:explosive",
    "load-behavior:ballistic",
  ],
  "Glute Bridge": ["apparatus:bodyweight", "angle-position:supine"],
  "Hip Thrust": ["angle-position:bench-supported"],
  "Single Leg Hip Thrust": [
    "angle-position:bench-supported",
    "limb-usage:single-leg",
  ],
  "Frog Pump": ["apparatus:bodyweight", "angle-position:supine"],
  "Leg Extension": ["apparatus:machine", "angle-position:seated"],
  "Terminal Knee Extension": ["apparatus:band", "angle-position:standing"],
  "Seated Hamstring Curl": ["apparatus:machine", "angle-position:seated"],
  "Lying Hamstring Curl": ["apparatus:machine", "angle-position:lying"],
  "Nordic Curl": ["apparatus:bodyweight", "tempo:slow-eccentric"],
  "Stability Ball Ham Curl": ["stability:swiss-ball", "angle-position:supine"],
  "Band Walk": ["apparatus:band", "limb-usage:wide-stance"],
  "Clamshell": ["apparatus:band", "angle-position:side-lying"],
  "Hip Abduction Machine": ["apparatus:machine", "angle-position:seated"],
  "Adductor Machine": ["apparatus:machine", "angle-position:seated"],
  "Copenhagen Plank": ["apparatus:bodyweight", "angle-position:side-support"],
  "Standing Calf Raise": ["angle-position:standing"],
  "Seated Calf Raise": ["angle-position:seated"],
  "Single Leg Calf Raise": ["angle-position:standing", "limb-usage:single-leg"],
  "Wall Tibialis Raise": ["apparatus:bodyweight", "angle-position:standing"],
  "Standing Tibialis Raise": ["apparatus:bodyweight", "angle-position:standing"],
  "Dumbbell Shoulder Press": ["apparatus:dumbbell", "angle-position:seated"],
  "Arnold Press": ["apparatus:dumbbell", "angle-position:seated"],
  "Push Press": ["apparatus:barbell", "tempo:explosive"],
  "Z Press": ["apparatus:barbell", "angle-position:seated"],
  "Landmine Press": ["apparatus:landmine", "angle-position:standing"],
  "Dumbbell Fly": ["apparatus:dumbbell", "angle-position:flat"],
  "Cable Fly": ["apparatus:cable", "angle-position:standing"],
  "Pec Deck": ["apparatus:machine", "angle-position:seated"],
  "Dumbbell Lateral Raise": ["apparatus:dumbbell", "angle-position:standing"],
  "Cable Lateral Raise": ["apparatus:cable", "angle-position:standing"],
  "Band Lateral Raise": ["apparatus:band", "angle-position:standing"],
  "Dumbbell Reverse Fly": ["apparatus:dumbbell", "angle-position:bent-over"],
  "Cable Reverse Fly": ["apparatus:cable", "angle-position:standing"],
  "Band Reverse Fly": ["apparatus:band", "angle-position:standing"],
  "Rear Delt Fly": ["apparatus:dumbbell", "angle-position:bent-over"],
  "Bent Over Row": ["apparatus:barbell", "angle-position:bent-over"],
  "Gorilla Row": [
    "apparatus:kettlebell",
    "limb-usage:alternating",
    "range-of-motion:dead-stop",
    "angle-position:bent-over",
  ],
  "Seal Row": ["apparatus:barbell", "angle-position:chest-supported"],
  "Renegade Row": ["apparatus:dumbbell", "angle-position:plank"],
  "Meadows Row": ["apparatus:landmine", "limb-usage:single-arm"],
  "Pull-Up": ["apparatus:bodyweight", "limb-usage:overhand-grip"],
  "Chin-Up": ["apparatus:bodyweight", "limb-usage:underhand-grip"],
  "Neutral Grip Pull-Up": ["apparatus:bodyweight", "limb-usage:neutral-grip"],
  "Lat Pulldown": ["apparatus:cable", "angle-position:seated"],
  "Dumbbell Pullover": ["apparatus:dumbbell", "angle-position:supine"],
  "Straight Arm Pulldown": ["apparatus:cable", "angle-position:standing"],
  "Hammer Curl": ["apparatus:dumbbell", "limb-usage:neutral-grip"],
  "Preacher Curl": ["angle-position:preacher"],
  "Incline Curl": ["apparatus:dumbbell", "angle-position:incline"],
  "Concentration Curl": ["apparatus:dumbbell", "angle-position:seated"],
  "Skullcrusher": ["apparatus:barbell", "angle-position:lying"],
  Pushdown: ["apparatus:cable", "angle-position:standing"],
  "Overhead Extension": ["angle-position:overhead"],
  Kickback: ["apparatus:dumbbell", "angle-position:bent-over"],
  "Wrist Curl": ["angle-position:seated"],
  "Behind Back Wrist Curl": ["angle-position:standing"],
  "Reverse Wrist Curl": ["angle-position:seated"],
  "Hammer Rotation": ["apparatus:dumbbell", "limb-usage:neutral-grip"],
  "Club Rotation": ["load-behavior:skill-complex"],
  "Band Pronation/Supination": ["apparatus:band"],
  "Band Shoulder Internal Rotation": ["apparatus:band"],
  "Cable Shoulder Internal Rotation": ["apparatus:cable"],
  "Band Shoulder External Rotation": ["apparatus:band"],
  "Cable Shoulder External Rotation": ["apparatus:cable"],
  "Side-Lying External Rotation": ["angle-position:side-lying"],
  "Scapular Push-Up": ["apparatus:bodyweight", "angle-position:floor"],
  "Scapular Pull-Up": ["apparatus:bodyweight", "limb-usage:overhand-grip"],
  "Wall Slide": ["apparatus:bodyweight", "angle-position:standing"],
  "Serratus Wall Slide": ["apparatus:bodyweight", "angle-position:standing"],
  "Russian Twist": ["apparatus:bodyweight", "angle-position:seated"],
  "Cable Woodchop": ["apparatus:cable", "load-behavior:skill-complex"],
  "Med Ball Rotational Throw": [
    "apparatus:medicine-ball",
    "tempo:explosive",
    "load-behavior:ballistic",
  ],
  "Landmine Rotation": ["apparatus:landmine"],
  "Pallof Press": ["apparatus:cable", "tempo:isometric"],
  "Renegade Hold": ["apparatus:dumbbell", "angle-position:plank"],
  "Single Arm Carry": ["limb-usage:single-arm", "load-behavior:loaded-carry"],
  Crunch: ["apparatus:bodyweight", "angle-position:supine"],
  "Sit-Up": ["apparatus:bodyweight", "angle-position:supine"],
  "Reverse Crunch": ["apparatus:bodyweight", "angle-position:supine"],
  "Hanging Leg Raise": ["apparatus:pull-up-bar"],
  Plank: ["apparatus:bodyweight", "angle-position:plank", "tempo:isometric"],
  "Ab Wheel Rollout": ["apparatus:ab-wheel", "range-of-motion:extended-rom"],
  "Dead Bug": ["apparatus:bodyweight", "angle-position:supine"],
  "Body Saw": ["apparatus:bodyweight", "angle-position:plank"],
  "Side Plank": ["apparatus:bodyweight", "angle-position:side-support"],
  "Suitcase Carry": [
    "limb-usage:single-arm",
    "limb-usage:offset",
    "load-behavior:loaded-carry",
  ],
  "Offset Hold": ["limb-usage:offset", "tempo:isometric"],
  "Farmer Carry": ["limb-usage:bilateral", "load-behavior:loaded-carry"],
  "Front Rack Carry": ["angle-position:front-loaded", "load-behavior:loaded-carry"],
  "Overhead Carry": ["angle-position:overhead", "load-behavior:loaded-carry"],
  "Waiter Carry": [
    "limb-usage:single-arm",
    "angle-position:overhead",
    "load-behavior:loaded-carry",
  ],
  "Bear Crawl": ["apparatus:bodyweight", "angle-position:quadruped"],
  "Leopard Crawl": ["apparatus:bodyweight", "angle-position:quadruped"],
  "Lateral Crawl": ["apparatus:bodyweight", "angle-position:quadruped"],
  "Box Jump": ["apparatus:box", "tempo:explosive", "load-behavior:ballistic"],
  "Broad Jump": ["apparatus:bodyweight", "tempo:explosive", "load-behavior:ballistic"],
  "Depth Jump": ["apparatus:box", "tempo:explosive", "load-behavior:ballistic"],
  "Single Leg Hop": [
    "apparatus:bodyweight",
    "limb-usage:single-leg",
    "tempo:explosive",
  ],
  "Hill Sprint": ["angle-position:incline", "load-behavior:cyclical"],
  "Sled Sprint": ["apparatus:sled", "load-behavior:cyclical"],
  "Shuttle Sprint": ["load-behavior:cyclical"],
  "Med Ball Chest Pass": ["apparatus:medicine-ball", "tempo:explosive"],
  "Rotational Throw": ["apparatus:medicine-ball", "tempo:explosive"],
  "Slam Ball Slam": ["apparatus:medicine-ball", "tempo:explosive"],
  "90/90 Hip Mobility": ["angle-position:seated"],
  "Thoracic Rotation": ["angle-position:quadruped"],
  "Couch Stretch": ["angle-position:half-kneeling"],
  "World's Greatest Stretch": ["angle-position:split-stance"],
  "90/90 Breathing": ["angle-position:supine", "tempo:tempo-controlled"],
  "Crocodile Breathing": ["angle-position:prone", "tempo:tempo-controlled"],
  "Dead Bug Breathing": ["angle-position:supine", "tempo:tempo-controlled"],
  "Supine Neck Flexion": ["angle-position:supine"],
  "Prone Neck Extension": ["angle-position:prone"],
  "Seated Neck Rotation": ["angle-position:seated"],
  Burpee: [
    "apparatus:bodyweight",
    "tempo:explosive",
    "load-behavior:skill-complex",
  ],
  Thruster: ["apparatus:dumbbell", "tempo:explosive", "load-behavior:skill-complex"],
  "Turkish Get-Up": ["apparatus:kettlebell", "load-behavior:skill-complex"],
  "Man Maker": ["apparatus:dumbbell", "load-behavior:skill-complex"],
  "Devil Press": [
    "apparatus:dumbbell",
    "tempo:explosive",
    "load-behavior:skill-complex",
  ],
  "Clean to Press": [
    "apparatus:barbell",
    "tempo:explosive",
    "load-behavior:skill-complex",
  ],
};

const SEMANTIC_VARIATION_ALIASES: Partial<Record<string, readonly string[]>> = {
  "Romanian Deadlift": ["rdl"],
  "Single Leg RDL": ["single leg romanian deadlift"],
  "Dumbbell Reverse Fly": ["rear delt fly"],
  "90/90 Breathing": ["breathing drill", "brace drill"],
  "World's Greatest Stretch": ["worlds greatest stretch"],
};

const SEMANTIC_VARIATION_MATCH_MODIFIER_SETS: Partial<
  Record<string, readonly (readonly ExerciseModifierId[])[]>
> = {
  "Goblet Squat": [
    ["apparatus:dumbbell", "angle-position:goblet"],
    ["apparatus:kettlebell", "angle-position:goblet"],
    ["angle-position:goblet"],
  ],
  "Incline Push-Up": [
    [
      "apparatus:bodyweight",
      "angle-position:incline",
      "limb-usage:standard-stance",
    ],
    ["apparatus:bodyweight", "angle-position:incline"],
  ],
  "Decline Push-Up": [
    [
      "apparatus:bodyweight",
      "angle-position:decline",
      "limb-usage:standard-stance",
    ],
    ["apparatus:bodyweight", "angle-position:decline"],
  ],
  "Sumo Squat": [
    ["apparatus:bodyweight", "limb-usage:wide-stance"],
    ["limb-usage:wide-stance"],
  ],
  "Sumo Deadlift": [
    ["apparatus:barbell", "limb-usage:wide-stance", "range-of-motion:dead-stop"],
    ["limb-usage:wide-stance", "range-of-motion:dead-stop"],
  ],
};

const semanticVariationId = (name: string) =>
  name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export const getCoreMovementPatternSemanticVariations = (
  id: CoreMovementPatternCardDefinition["id"],
): CoreMovementSemanticVariation[] =>
  getCoreMovementPatternVariationNames(id).map((name) => ({
    id: `${id}-${semanticVariationId(name)}`,
    name,
    modifierIds: [...(SEMANTIC_VARIATION_MODIFIER_IDS[name] || [])],
    matchModifierSets: [
      [...(SEMANTIC_VARIATION_MODIFIER_IDS[name] || [])],
      ...(SEMANTIC_VARIATION_MATCH_MODIFIER_SETS[name] || []).map((modifierIds) => [
        ...modifierIds,
      ]),
    ],
    aliases: [...(SEMANTIC_VARIATION_ALIASES[name] || [])],
  }));

const commonBodyweightModifiers: ExerciseModifierId[] = [
  "apparatus:bodyweight",
  "stability:stable",
  "range-of-motion:full-rom",
];

export const CORE_MOVEMENT_PATTERN_CARD_DEFINITIONS = [
  {
    id: "core-squat",
    name: "Squat",
    category: "Lower Body Compound",
    coreMovementId: "squat",
    movementPatternId: "squat",
    description: "Knee-dominant lower body lowering and standing pattern.",
    body: "Legs",
    muscles: "Quads / Glutes / Core",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "limb-usage:bilateral",
    ],
    aliases: ["air squat", "bodyweight squat", "goblet squat", "front squat", "back squat"],
  },
  {
    id: "core-hinge",
    name: "Hinge",
    category: "Lower Body Compound",
    coreMovementId: "hinge",
    movementPatternId: "hinge",
    description: "Hip-dominant flexion and extension pattern.",
    body: "Posterior Chain",
    muscles: "Hamstrings / Glutes / Low Back",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "limb-usage:bilateral",
    ],
    aliases: ["deadlift", "rdl", "romanian deadlift", "good morning", "swing"],
  },
  {
    id: "core-lunge",
    name: "Lunge",
    category: "Lower Body Compound",
    coreMovementId: "lunge",
    movementPatternId: "lunge",
    description: "Split stance lowering pattern for single-leg control.",
    body: "Legs",
    muscles: "Quads / Glutes / Hamstrings",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "limb-usage:unilateral",
    ],
    aliases: ["reverse lunge", "forward lunge", "walking lunge", "split squat"],
  },
  {
    id: "core-step-up",
    name: "Step-Up",
    category: "Lower Body Compound",
    coreMovementId: "step-up",
    movementPatternId: "step-up",
    description: "Vertical stepping movement onto or down from elevation.",
    body: "Legs",
    muscles: "Quads / Glutes / Calves",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "limb-usage:unilateral",
    ],
    aliases: ["box step-up", "lateral step-up", "step down", "box step"],
  },
  {
    id: "core-hip-thrust-bridge",
    name: "Hip Thrust / Bridge",
    category: "Lower Body Compound",
    coreMovementId: "hip-thrust-bridge",
    movementPatternId: "hip-thrust-bridge",
    description: "Horizontal hip extension with reduced spinal demand.",
    body: "Glutes",
    muscles: "Glutes / Hamstrings / Core",
    goal: "Hypertrophy",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      "apparatus:bodyweight",
      "angle-position:supine",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["glute bridge", "hip thrust", "barbell hip thrust"],
  },
  {
    id: "core-knee-extension",
    name: "Knee Extension",
    category: "Lower Body Isolation",
    coreMovementId: "knee-extension",
    movementPatternId: "knee-extension",
    description: "Knee extension isolation movement.",
    body: "Legs",
    muscles: "Quads",
    goal: "Hypertrophy",
    equipment: "Machine",
    level: "Beginner",
    modifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["leg extension", "terminal knee extension"],
  },
  {
    id: "core-knee-flexion",
    name: "Knee Flexion",
    category: "Lower Body Isolation",
    coreMovementId: "knee-flexion",
    movementPatternId: "knee-flexion",
    description: "Hamstring knee-flexion isolation movement.",
    body: "Hamstrings",
    muscles: "Hamstrings / Calves",
    goal: "Hypertrophy",
    equipment: "Machine",
    level: "Beginner",
    modifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["leg curl", "hamstring curl", "nordic curl"],
  },
  {
    id: "core-hip-abduction",
    name: "Hip Abduction",
    category: "Lower Body Isolation",
    coreMovementId: "hip-abduction",
    movementPatternId: "hip-abduction",
    description: "Moving the leg away from midline.",
    body: "Hips / Glutes",
    muscles: "Glute Med / Glute Min",
    goal: "Stability",
    equipment: "Band",
    level: "Beginner",
    modifierIds: [
      "apparatus:band",
      "angle-position:standing",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["band walk", "clamshell", "abduction machine"],
  },
  {
    id: "core-hip-adduction",
    name: "Hip Adduction",
    category: "Lower Body Isolation",
    coreMovementId: "hip-adduction",
    movementPatternId: "hip-adduction",
    description: "Moving the leg toward midline.",
    body: "Hips / Adductors",
    muscles: "Adductors / Pelvic Stabilizers",
    goal: "Stability",
    equipment: "Machine",
    level: "Beginner",
    modifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["adductor machine", "copenhagen plank"],
  },
  {
    id: "core-hip-internal-rotation",
    name: "Hip Internal Rotation",
    category: "Lower Body Isolation",
    coreMovementId: "hip-internal-rotation",
    movementPatternId: "hip-internal-rotation",
    description: "Rotating the femur inward through the hip.",
    body: "Hips",
    muscles: "Hip Rotators / Glutes",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "angle-position:seated",
    ],
    aliases: ["hip ir", "internal hip rotation", "hip internal rotation"],
  },
  {
    id: "core-hip-external-rotation",
    name: "Hip External Rotation",
    category: "Lower Body Isolation",
    coreMovementId: "hip-external-rotation",
    movementPatternId: "hip-external-rotation",
    description: "Rotating the femur outward through the hip.",
    body: "Hips / Glutes",
    muscles: "Deep Hip Rotators / Glutes",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "angle-position:seated",
    ],
    aliases: ["hip er", "external hip rotation", "hip external rotation", "clamshell"],
  },
  {
    id: "core-calf-raise",
    name: "Calf Raise",
    category: "Lower Body Isolation",
    coreMovementId: "calf-raise",
    movementPatternId: "calf-raise",
    description: "Plantar flexion through the ankle.",
    body: "Calves",
    muscles: "Calves / Foot Intrinsics",
    goal: "Hypertrophy",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "angle-position:standing",
    ],
    aliases: ["plantar flexion", "standing calf raise", "seated calf raise"],
  },
  {
    id: "core-tibialis-raise",
    name: "Tibialis Raise",
    category: "Lower Body Isolation",
    coreMovementId: "tibialis-raise",
    movementPatternId: "tibialis-raise",
    description: "Dorsiflexion-focused ankle isolation.",
    body: "Lower Legs",
    muscles: "Tibialis Anterior",
    goal: "Recovery",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "angle-position:standing",
    ],
    aliases: ["ankle dorsiflexion", "toe raise", "shin raise", "tib raise", "tibialis"],
  },
  {
    id: "core-chest-press",
    name: "Chest Press",
    category: "Upper Push",
    coreMovementId: "chest-press",
    movementPatternId: "chest-press",
    description: "Pressing away from the torso with chest emphasis.",
    body: "Chest",
    muscles: "Pecs / Triceps / Shoulders",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "limb-usage:bilateral",
    ],
    aliases: ["push-up", "push up", "bench press", "dumbbell press", "chest press"],
  },
  {
    id: "core-shoulder-press",
    name: "Shoulder Press",
    category: "Upper Push",
    coreMovementId: "shoulder-press",
    movementPatternId: "shoulder-press",
    description: "Pressing overhead or upward.",
    body: "Shoulders",
    muscles: "Shoulders / Triceps / Core",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["overhead press", "military press", "dumbbell shoulder press"],
  },
  {
    id: "core-chest-fly",
    name: "Chest Fly",
    category: "Upper Push",
    coreMovementId: "chest-fly",
    movementPatternId: "chest-fly",
    description: "Shoulder horizontal adduction with chest emphasis.",
    body: "Chest",
    muscles: "Pecs / Anterior Delts",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:flat",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["pec fly", "dumbbell fly", "cable fly", "machine fly"],
  },
  {
    id: "core-lateral-raise",
    name: "Lateral Raise",
    category: "Upper Push",
    coreMovementId: "lateral-raise",
    movementPatternId: "lateral-raise",
    description: "Shoulder abduction isolation for lateral delts.",
    body: "Shoulders",
    muscles: "Side Delts / Traps",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["side raise", "dumbbell lateral raise", "shoulder abduction"],
  },
  {
    id: "core-row",
    name: "Row",
    category: "Upper Pull",
    coreMovementId: "row",
    movementPatternId: "row",
    description: "Pulling toward the torso.",
    body: "Back",
    muscles: "Lats / Mid Back / Biceps",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["db row", "dumbbell row", "cable row", "gorilla row", "renegade row"],
  },
  {
    id: "core-vertical-pull",
    name: "Vertical Pull",
    category: "Upper Pull",
    coreMovementId: "vertical-pull",
    movementPatternId: "vertical-pull",
    description: "Pulling down or pulling the body upward.",
    body: "Back",
    muscles: "Lats / Upper Back / Biceps",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "limb-usage:bilateral",
    ],
    aliases: ["pull-up", "pull up", "chin-up", "chin up", "lat pulldown"],
  },
  {
    id: "core-pullover",
    name: "Pullover",
    category: "Upper Pull",
    coreMovementId: "pullover",
    movementPatternId: "pullover",
    description: "Shoulder extension pattern with lat emphasis.",
    body: "Back",
    muscles: "Lats / Chest / Triceps",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:supine",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["dumbbell pullover", "straight arm pulldown"],
  },
  {
    id: "core-reverse-fly",
    name: "Reverse Fly",
    category: "Upper Pull",
    coreMovementId: "reverse-fly",
    movementPatternId: "reverse-fly",
    description: "Shoulder horizontal abduction with rear-delt and upper-back emphasis.",
    body: "Shoulders",
    muscles: "Rear Delts / Mid Back / Rotator Cuff",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:prone",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["rear delt fly", "reverse dumbbell fly", "rear delt raise"],
  },
  {
    id: "core-curl",
    name: "Curl",
    category: "Arm Isolation",
    coreMovementId: "curl",
    movementPatternId: "curl",
    description: "Elbow flexion for biceps and arm strength.",
    body: "Arms",
    muscles: "Biceps / Forearms",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["biceps curl", "hammer curl", "preacher curl"],
  },
  {
    id: "core-triceps-extension",
    name: "Triceps Extension",
    category: "Arm Isolation",
    coreMovementId: "triceps-extension",
    movementPatternId: "triceps-extension",
    description: "Elbow extension for triceps strength.",
    body: "Arms",
    muscles: "Triceps / Shoulders",
    goal: "Hypertrophy",
    equipment: "Cable",
    level: "Beginner",
    modifierIds: [
      "apparatus:cable",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["pushdown", "pressdown", "skullcrusher", "overhead triceps extension"],
  },
  {
    id: "core-wrist-flexion",
    name: "Wrist Flexion",
    category: "Arm Isolation",
    coreMovementId: "wrist-flexion",
    movementPatternId: "wrist-flexion",
    description: "Flexing the wrist against resistance.",
    body: "Forearms",
    muscles: "Forearm Flexors / Grip",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:seated",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["wrist curl", "forearm curl"],
  },
  {
    id: "core-wrist-extension",
    name: "Wrist Extension",
    category: "Arm Isolation",
    coreMovementId: "wrist-extension",
    movementPatternId: "wrist-extension",
    description: "Extending the wrist against resistance.",
    body: "Forearms",
    muscles: "Forearm Extensors / Grip",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:seated",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["reverse wrist curl"],
  },
  {
    id: "core-wrist-rotation",
    name: "Wrist Rotation",
    category: "Arm Isolation",
    coreMovementId: "wrist-rotation",
    movementPatternId: "wrist-rotation",
    description: "Pronation, supination, and rotational wrist control.",
    body: "Forearms",
    muscles: "Forearms / Grip",
    goal: "Stability",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "angle-position:seated",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["pronation", "supination", "hammer rotation", "wrist rotation"],
  },
  {
    id: "core-shoulder-internal-rotation",
    name: "Shoulder Internal Rotation",
    category: "Arm Isolation",
    coreMovementId: "shoulder-internal-rotation",
    movementPatternId: "shoulder-internal-rotation",
    description: "Rotator-cuff internal rotation pattern.",
    body: "Shoulders",
    muscles: "Rotator Cuff / Anterior Shoulder",
    goal: "Recovery",
    equipment: "Band",
    level: "Beginner",
    modifierIds: [
      "apparatus:band",
      "angle-position:standing",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["shoulder ir", "internal rotation", "shoulder internal rotation"],
  },
  {
    id: "core-shoulder-external-rotation",
    name: "Shoulder External Rotation",
    category: "Arm Isolation",
    coreMovementId: "shoulder-external-rotation",
    movementPatternId: "shoulder-external-rotation",
    description: "Rotator-cuff external rotation pattern.",
    body: "Shoulders",
    muscles: "Rotator Cuff / Rear Delts",
    goal: "Recovery",
    equipment: "Band",
    level: "Beginner",
    modifierIds: [
      "apparatus:band",
      "angle-position:standing",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["shoulder er", "external rotation", "shoulder external rotation"],
  },
  {
    id: "core-scapular-control",
    name: "Scapular Control",
    category: "Arm Isolation",
    coreMovementId: "scapular-control",
    movementPatternId: "scapular-control",
    description: "Scapular retraction, protraction, elevation, depression, or control drill.",
    body: "Upper Back / Shoulders",
    muscles: "Mid Traps / Lower Traps / Serratus",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "load-behavior:skill-complex",
    ],
    aliases: ["scapular control", "scapular retraction", "scapular protraction", "face pull"],
  },
  {
    id: "core-rotation",
    name: "Rotation",
    category: "Core",
    coreMovementId: "rotation",
    movementPatternId: "rotation",
    description: "Producing rotational force through the trunk and hips.",
    body: "Core",
    muscles: "Obliques / Hips / Shoulders",
    goal: "Power",
    equipment: "Cable",
    level: "Beginner",
    modifierIds: [
      "apparatus:cable",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
    aliases: ["wood chop", "russian twist", "rotational throw"],
  },
  {
    id: "core-anti-rotation",
    name: "Anti-Rotation",
    category: "Core",
    coreMovementId: "anti-rotation",
    movementPatternId: "anti-rotation",
    description: "Resisting rotational force through the trunk.",
    body: "Core",
    muscles: "Obliques / Deep Core / Glutes",
    goal: "Stability",
    equipment: "Cable",
    level: "Beginner",
    modifierIds: [
      "apparatus:cable",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
    ],
    aliases: ["pallof press", "anti rotation", "anti-rotation", "renegade row", "suitcase carry"],
  },
  {
    id: "core-flexion",
    name: "Flexion",
    category: "Core",
    coreMovementId: "flexion",
    movementPatternId: "flexion",
    description: "Trunk flexion or spinal flexion control.",
    body: "Core",
    muscles: "Abs / Hip Flexors",
    goal: "Hypertrophy",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
      "angle-position:supine",
    ],
    aliases: ["crunch", "sit-up", "reverse crunch", "hanging leg raise"],
  },
  {
    id: "core-anti-extension",
    name: "Anti-Extension",
    category: "Core",
    coreMovementId: "anti-extension",
    movementPatternId: "anti-extension",
    description: "Resisting spinal extension.",
    body: "Core",
    muscles: "Deep Core / Abs / Glutes",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
    aliases: ["plank", "dead bug", "ab wheel rollout", "body saw"],
  },
  {
    id: "core-anti-lateral-flexion",
    name: "Anti-Lateral Flexion",
    category: "Core",
    coreMovementId: "anti-lateral-flexion",
    movementPatternId: "anti-lateral-flexion",
    description: "Resisting side bending.",
    body: "Core",
    muscles: "Obliques / Deep Core / Grip",
    goal: "Stability",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "limb-usage:offset",
      "stability:stable",
      "load-behavior:loaded-carry",
    ],
    aliases: ["side plank", "suitcase carry", "offset hold", "anti lateral flexion"],
  },
  {
    id: "core-carry",
    name: "Carry",
    category: "Athletic",
    coreMovementId: "carry",
    movementPatternId: "carry",
    description: "Loaded locomotion pattern.",
    body: "Full Body",
    muscles: "Core / Grip / Traps / Glutes",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    modifierIds: [
      "apparatus:dumbbell",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:loaded-carry",
    ],
    aliases: ["farmer carry", "suitcase carry", "front rack carry"],
  },
  {
    id: "core-crawl",
    name: "Crawl",
    category: "Athletic",
    coreMovementId: "crawl",
    movementPatternId: "crawl",
    description: "Ground-based quadruped locomotion and coordination.",
    body: "Full Body",
    muscles: "Core / Shoulders / Quads",
    goal: "Conditioning",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:cyclical",
    ],
    aliases: ["bear crawl", "leopard crawl", "lateral crawl"],
  },
  {
    id: "core-jump",
    name: "Jump",
    category: "Athletic",
    coreMovementId: "jump",
    movementPatternId: "jump",
    description: "Explosive takeoff and landing pattern.",
    body: "Full Body",
    muscles: "Quads / Glutes / Calves",
    goal: "Power",
    equipment: "Bodyweight",
    level: "Intermediate",
    modifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
    aliases: ["box jump", "broad jump", "single leg hop", "jump"],
  },
  {
    id: "core-sprint",
    name: "Sprint",
    category: "Athletic",
    coreMovementId: "sprint",
    movementPatternId: "sprint",
    description: "Rapid locomotion, acceleration, or max velocity pattern.",
    body: "Full Body",
    muscles: "Glutes / Hamstrings / Calves",
    goal: "Conditioning",
    equipment: "Bodyweight",
    level: "Intermediate",
    modifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:cyclical",
    ],
    aliases: ["hill sprint", "shuttle sprint", "sled sprint", "sprint"],
  },
  {
    id: "core-throw",
    name: "Throw",
    category: "Athletic",
    coreMovementId: "throw",
    movementPatternId: "throw",
    description: "Explosive force projection through an implement.",
    body: "Full Body",
    muscles: "Core / Shoulders / Chest / Glutes",
    goal: "Power",
    equipment: "Medicine Ball",
    level: "Beginner",
    modifierIds: [
      "apparatus:medicine-ball",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
    aliases: ["med ball throw", "rotational throw", "slam ball", "medicine ball throw"],
  },
  {
    id: "core-mobility",
    name: "Mobility",
    category: "Mobility",
    coreMovementId: "mobility",
    movementPatternId: "mobility",
    description: "Movement quality, range, and control drills.",
    body: "Mobility",
    muscles: "Hips / Upper Back / Shoulders",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
    aliases: ["mobility drill", "world's greatest stretch", "90/90 hip mobility", "couch stretch"],
  },
  {
    id: "core-breathing-bracing",
    name: "Breathing / Bracing",
    category: "Mobility",
    coreMovementId: "breathing-bracing",
    movementPatternId: "breathing-bracing",
    description: "Breathing mechanics, trunk pressure, and bracing coordination.",
    body: "Core / Mobility",
    muscles: "Diaphragm / Deep Core / Obliques",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
    aliases: ["90/90 breathing", "crocodile breathing", "brace drill", "breathing", "bracing"],
  },
  {
    id: "core-neck-flexion",
    name: "Neck Flexion",
    category: "Cervical Isolation",
    coreMovementId: "neck-flexion",
    movementPatternId: "neck-flexion",
    description: "Cervical flexion isolation and control.",
    body: "Neck",
    muscles: "Deep Neck Flexors / Anterior Neck",
    goal: "Recovery",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
    ],
    aliases: ["cervical flexion", "neck flexion"],
  },
  {
    id: "core-neck-extension",
    name: "Neck Extension",
    category: "Cervical Isolation",
    coreMovementId: "neck-extension",
    movementPatternId: "neck-extension",
    description: "Cervical extension isolation and control.",
    body: "Neck",
    muscles: "Cervical Extensors / Upper Traps",
    goal: "Recovery",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
    ],
    aliases: ["cervical extension", "neck extension"],
  },
  {
    id: "core-neck-rotation",
    name: "Neck Rotation",
    category: "Cervical Isolation",
    coreMovementId: "neck-rotation",
    movementPatternId: "neck-rotation",
    description: "Cervical rotation isolation and control.",
    body: "Neck",
    muscles: "Cervical Rotators / Upper Traps",
    goal: "Recovery",
    equipment: "Bodyweight",
    level: "Beginner",
    modifierIds: [
      ...commonBodyweightModifiers,
    ],
    aliases: ["cervical rotation", "neck rotation"],
  },
  {
    id: "core-integrated-movement",
    name: "Integrated Movement",
    category: "Integrated",
    coreMovementId: "integrated-movement",
    movementPatternId: "integrated-movement",
    description: "Multi-pattern exercise combining several movement demands.",
    body: "Full Body",
    muscles: "Core / Glutes / Shoulders / Quads",
    goal: "Conditioning",
    equipment: "Bodyweight",
    level: "Intermediate",
    modifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
    aliases: ["burpee", "thruster", "turkish get-up", "man maker", "devil press", "clean to press", "complex", "combo"],
    integrated: true,
  },
] as const satisfies readonly CoreMovementPatternCardDefinition[];

export const CORE_MOVEMENT_PATTERN_CARD_COUNT =
  CORE_MOVEMENT_PATTERN_CARD_DEFINITIONS.length;

export const coreMovementPatternCardToExercise = (
  definition: CoreMovementPatternCardDefinition,
): ExerciseCatalogItem => ({
  id: definition.id,
  name: definition.name,
  body: definition.body,
  muscles: definition.muscles,
  pattern: definition.name,
  goal: definition.goal,
  equipment: definition.equipment,
  level: definition.level,
  image: getExerciseImage(definition.body, definition.id),
  cue: definition.description,
});
