import type { ExerciseCatalogItem } from "@/types";

export type Exercise = ExerciseCatalogItem;

const freeExerciseDbBaseUrl =
  "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

const freeExerciseDbImage = (exerciseId: string, frame = 0) =>
  `${freeExerciseDbBaseUrl}/${exerciseId}/${frame}.jpg`;

const exerciseSpecificImages: Record<string, string> = {
  "core-squat": freeExerciseDbImage("Bodyweight_Squat"),
  "core-hinge": freeExerciseDbImage("Romanian_Deadlift"),
  "core-lunge": freeExerciseDbImage("Bodyweight_Walking_Lunge"),
  "core-step-up": freeExerciseDbImage("Step-up_with_Knee_Raise"),
  "core-hip-thrust-bridge": freeExerciseDbImage("Barbell_Hip_Thrust"),
  "core-knee-extension": freeExerciseDbImage("Leg_Extensions"),
  "core-knee-flexion": freeExerciseDbImage("Seated_Leg_Curl"),
  "core-hip-abduction": freeExerciseDbImage("Thigh_Abductor"),
  "core-hip-adduction": freeExerciseDbImage("Thigh_Adductor"),
  "core-hip-internal-rotation": freeExerciseDbImage("Hip_Circles_prone"),
  "core-hip-external-rotation": freeExerciseDbImage("Hip_Circles_prone", 1),
  "core-calf-raise": freeExerciseDbImage("Standing_Calf_Raises"),
  "core-tibialis-raise": freeExerciseDbImage("Smith_Machine_Reverse_Calf_Raises"),
  "core-chest-press": freeExerciseDbImage("Push-Up_Wide"),
  "core-shoulder-press": freeExerciseDbImage("Dumbbell_Shoulder_Press"),
  "core-chest-fly": freeExerciseDbImage("Dumbbell_Flyes"),
  "core-lateral-raise": freeExerciseDbImage("Side_Lateral_Raise"),
  "core-row": freeExerciseDbImage("Bent_Over_Two-Dumbbell_Row"),
  "core-vertical-pull": freeExerciseDbImage("Chin-Up"),
  "core-pullover": freeExerciseDbImage("Bent-Arm_Dumbbell_Pullover"),
  "core-reverse-fly": freeExerciseDbImage("Reverse_Flyes"),
  "core-curl": freeExerciseDbImage("Dumbbell_Bicep_Curl"),
  "core-triceps-extension": freeExerciseDbImage("Triceps_Pushdown"),
  "core-wrist-flexion": freeExerciseDbImage(
    "Seated_Dumbbell_Palms-Up_Wrist_Curl",
  ),
  "core-wrist-extension": freeExerciseDbImage(
    "Seated_Dumbbell_Palms-Down_Wrist_Curl",
  ),
  "core-wrist-rotation": freeExerciseDbImage("Dumbbell_Lying_Pronation"),
  "core-shoulder-internal-rotation": freeExerciseDbImage(
    "Internal_Rotation_with_Band",
  ),
  "core-shoulder-external-rotation": freeExerciseDbImage(
    "External_Rotation_with_Band",
  ),
  "core-scapular-control": freeExerciseDbImage("Face_Pull"),
  "core-rotation": freeExerciseDbImage("Standing_Cable_Wood_Chop"),
  "core-anti-rotation": freeExerciseDbImage("Pallof_Press"),
  "core-flexion": freeExerciseDbImage("3_4_Sit-Up"),
  "core-anti-extension": freeExerciseDbImage("Plank"),
  "core-anti-lateral-flexion": freeExerciseDbImage("Farmers_Walk"),
  "core-carry": freeExerciseDbImage("Farmers_Walk"),
  "core-crawl": freeExerciseDbImage("Spider_Crawl"),
  "core-jump": freeExerciseDbImage("Front_Box_Jump"),
  "core-sprint": freeExerciseDbImage("Wind_Sprints"),
  "core-throw": freeExerciseDbImage("Medicine_Ball_Chest_Pass"),
  "core-mobility": freeExerciseDbImage("Worlds_Greatest_Stretch"),
  "core-breathing-bracing": freeExerciseDbImage("Plank", 1),
  "core-neck-flexion": freeExerciseDbImage(
    "Isometric_Neck_Exercise_-_Front_And_Back",
  ),
  "core-neck-extension": freeExerciseDbImage(
    "Isometric_Neck_Exercise_-_Front_And_Back",
    1,
  ),
  "core-neck-rotation": freeExerciseDbImage("Isometric_Neck_Exercise_-_Sides"),
  "core-integrated-movement": freeExerciseDbImage("Kettlebell_Thruster"),

  "goblet-squat": freeExerciseDbImage("Goblet_Squat"),
  "db-front-squat": freeExerciseDbImage("Front_Squats_With_Two_Kettlebells"),
  "barbell-back-squat": freeExerciseDbImage("Barbell_Squat"),
  "box-squat": freeExerciseDbImage("Box_Squat"),
  "split-squat": freeExerciseDbImage("Split_Squat_with_Dumbbells"),
  "bulgarian-split-squat": freeExerciseDbImage("Suspended_Split_Squat"),
  "step-up": freeExerciseDbImage("Step-up_with_Knee_Raise"),
  "lateral-step-up": freeExerciseDbImage("Step-up_with_Knee_Raise", 1),
  "db-romanian-deadlift": freeExerciseDbImage("Stiff-Legged_Dumbbell_Deadlift"),
  "barbell-romanian-deadlift": freeExerciseDbImage("Romanian_Deadlift"),
  "conventional-deadlift": freeExerciseDbImage("Barbell_Deadlift"),
  "trap-bar-deadlift": freeExerciseDbImage("Trap_Bar_Deadlift"),
  "single-leg-rdl": freeExerciseDbImage("Kettlebell_One-Legged_Deadlift"),
  "hip-thrust": freeExerciseDbImage("Barbell_Hip_Thrust"),
  "glute-bridge": freeExerciseDbImage("Single_Leg_Glute_Bridge"),
  "cable-pull-through": freeExerciseDbImage("Pull_Through"),
  "reverse-lunge": freeExerciseDbImage("Dumbbell_Rear_Lunge"),
  "walking-lunge": freeExerciseDbImage("Dumbbell_Lunges"),
  "forward-lunge": freeExerciseDbImage("Bodyweight_Walking_Lunge"),
  "lateral-lunge": freeExerciseDbImage("Barbell_Side_Split_Squat"),
  "curtsy-lunge": freeExerciseDbImage("Crossover_Reverse_Lunge"),
  plank: freeExerciseDbImage("Plank"),
  "dead-bug": freeExerciseDbImage("Dead_Bug"),
  "stability-ball-rollout": freeExerciseDbImage("Exercise_Ball_Pull-In"),
  "ab-wheel": freeExerciseDbImage("Ab_Roller"),
  "pallof-press": freeExerciseDbImage("Pallof_Press"),
  "half-kneeling-pallof-press": freeExerciseDbImage("Pallof_Press_With_Rotation"),
  "cable-hold": freeExerciseDbImage("Pallof_Press", 1),
  "suitcase-carry": freeExerciseDbImage("Farmers_Walk"),
  "single-arm-farmer-carry": freeExerciseDbImage("Farmers_Walk", 1),
  "cable-wood-chop": freeExerciseDbImage("Standing_Cable_Wood_Chop"),
  "med-ball-rotations": freeExerciseDbImage("Medicine_Ball_Full_Twist"),
  "push-up": freeExerciseDbImage("Push-Up_Wide"),
  "incline-push-up": freeExerciseDbImage("Incline_Push-Up"),
  "db-bench-press": freeExerciseDbImage("Dumbbell_Bench_Press"),
  "barbell-bench-press": freeExerciseDbImage(
    "Barbell_Bench_Press_-_Medium_Grip",
  ),
  "incline-db-press": freeExerciseDbImage("Incline_Dumbbell_Press"),
  "db-shoulder-press": freeExerciseDbImage("Dumbbell_Shoulder_Press"),
  "arnold-press": freeExerciseDbImage("Arnold_Dumbbell_Press"),
  "landmine-press": freeExerciseDbImage("Landmine_Linear_Jammer"),
  "barbell-overhead-press": freeExerciseDbImage("Standing_Military_Press"),
  "bent-over-row": freeExerciseDbImage("Bent_Over_Barbell_Row"),
  "one-arm-db-row": freeExerciseDbImage("One-Arm_Dumbbell_Row"),
  "chest-supported-row": freeExerciseDbImage("Incline_Bench_Pull"),
  "cable-row": freeExerciseDbImage("Seated_Cable_Rows"),
  "lat-pulldown": freeExerciseDbImage("Wide-Grip_Lat_Pulldown"),
  "assisted-pull-up": freeExerciseDbImage("Band_Assisted_Pull-Up"),
  "pull-up": freeExerciseDbImage("Wide-Grip_Rear_Pull-Up"),
  "chin-up": freeExerciseDbImage("Chin-Up"),
  "lateral-raise": freeExerciseDbImage("Side_Lateral_Raise"),
  "front-raise": freeExerciseDbImage("Front_Dumbbell_Raise"),
  "rear-delt-fly": freeExerciseDbImage("Reverse_Flyes"),
  "face-pull": freeExerciseDbImage("Face_Pull"),
  "yt-raises": freeExerciseDbImage("Dumbbell_Scaption"),
  "frog-pump": freeExerciseDbImage("Single_Leg_Glute_Bridge", 1),
  "cable-kickback": freeExerciseDbImage("One-Legged_Cable_Kickback"),
  "glute-bridge-march": freeExerciseDbImage("Single_Leg_Glute_Bridge"),
  "hip-mobility-flow": freeExerciseDbImage("Worlds_Greatest_Stretch"),
  "90-90-hip-rotation": freeExerciseDbImage("Hip_Circles_prone"),
  "thoracic-rotation": freeExerciseDbImage("Torso_Rotation"),
  "worlds-greatest-stretch": freeExerciseDbImage("Worlds_Greatest_Stretch"),
  "ankle-dorsiflexion-drill": freeExerciseDbImage(
    "Calf_Stretch_Hands_Against_Wall",
  ),
  "box-jump": freeExerciseDbImage("Front_Box_Jump"),
  "broad-jump": freeExerciseDbImage("Standing_Long_Jump"),
  "med-ball-slam": freeExerciseDbImage("Overhead_Slam"),
  "med-ball-chest-pass": freeExerciseDbImage("Medicine_Ball_Chest_Pass"),
  "kettlebell-swing": freeExerciseDbImage("One-Arm_Kettlebell_Swings"),
  "kettlebell-clean": freeExerciseDbImage("One-Arm_Kettlebell_Clean"),
  "db-thruster": freeExerciseDbImage("Kettlebell_Thruster"),
  burpee:
    "https://commons.wikimedia.org/wiki/Special:FilePath/Airborne%20Burpee.jpg?width=900",
  "farmer-carry": freeExerciseDbImage("Farmers_Walk"),
  "sled-push": freeExerciseDbImage("Sled_Push"),
  "sled-pull": freeExerciseDbImage("Sled_Drag_-_Harness"),
};

const bodyPartImages: Record<string, string[]> = {
  Legs: [
    "https://images.unsplash.com/photo-1434682881908-b43d0467b798?q=80&w=900",
    "https://images.unsplash.com/photo-1534368420009-621bfab424a8?q=80&w=900",
    "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?q=80&w=900",
  ],
  Hamstrings: [
    "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?q=80&w=900",
    "https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=900",
  ],
  Glutes: [
    "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=900",
    "https://images.unsplash.com/photo-1594381898411-846e7d193883?q=80&w=900",
  ],
  Core: [
    "https://images.unsplash.com/photo-1566241142559-40e1dab266c6?q=80&w=900",
    "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=900",
    "https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=900",
  ],
  Chest: [
    "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?q=80&w=900",
    "https://images.unsplash.com/photo-1571019613914-85f342c6a11e?q=80&w=900",
  ],
  Back: [
    "https://images.unsplash.com/photo-1581009137042-c552e485697a?q=80&w=900",
    "https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?q=80&w=900",
  ],
  Shoulders: [
    "https://images.unsplash.com/photo-1534258936925-c58bed479fcb?q=80&w=900",
    "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=900",
  ],
  Mobility: [
    "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=900",
    "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=900",
  ],
  "Full Body": [
    "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=900",
    "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=900",
  ],
  "Posterior Chain": [
    "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=900",
    "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?q=80&w=900",
  ],
};

export function getExerciseImage(body: string, id?: string) {
  if (id && exerciseSpecificImages[id]) return exerciseSpecificImages[id];

  const images = bodyPartImages[body] || bodyPartImages["Full Body"];
  return images[0];
}
const makeExercise = (exercise: Omit<Exercise, "image">): Exercise => ({
  ...exercise,
  image: getExerciseImage(exercise.body, exercise.id),
});

export const exerciseLibrary: Exercise[] = [
  makeExercise({
    id: "goblet-squat",
    name: "Goblet Squat",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Squat",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Brace your core, keep your chest tall, and drive through the whole foot.",
  }),
  makeExercise({
    id: "db-front-squat",
    name: "DB Front Squat",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Squat",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Keep the weights high, ribs stacked, and knees tracking with your toes.",
  }),
  makeExercise({
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Squat",
    goal: "Strength",
    equipment: "Barbell",
    level: "Intermediate",
    cue: "Create tension before you descend and keep pressure through the whole foot.",
  }),
  makeExercise({
    id: "box-squat",
    name: "Box Squat",
    body: "Legs",
    muscles: "Quads • Glutes • Hamstrings",
    pattern: "Squat",
    goal: "Strength",
    equipment: "Box",
    level: "Beginner",
    cue: "Sit back with control, stay braced, then drive up without rocking.",
  }),
  makeExercise({
    id: "split-squat",
    name: "Split Squat",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Squat",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Stay tall, drop straight down, and keep the front foot rooted.",
  }),
  makeExercise({
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Squat",
    goal: "Hypertrophy",
    equipment: "Bench",
    level: "Intermediate",
    cue: "Lower with control and drive through the front leg without bouncing.",
  }),
  makeExercise({
    id: "step-up",
    name: "Step-Up",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Squat",
    goal: "Stability",
    equipment: "Box",
    level: "Beginner",
    cue: "Own the top position and avoid pushing off the back foot.",
  }),
  makeExercise({
    id: "lateral-step-up",
    name: "Lateral Step-Up",
    body: "Legs",
    muscles: "Glutes • Quads • Hip Stabilizers",
    pattern: "Squat",
    goal: "Stability",
    equipment: "Box",
    level: "Intermediate",
    cue: "Step sideways with control and keep the knee stacked over the foot.",
  }),

  makeExercise({
    id: "db-romanian-deadlift",
    name: "DB Romanian Deadlift",
    body: "Hamstrings",
    muscles: "Hamstrings • Glutes • Low Back",
    pattern: "Hinge",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Push your hips back, keep the weights close, and feel the hamstrings load.",
  }),
  makeExercise({
    id: "barbell-romanian-deadlift",
    name: "Barbell Romanian Deadlift",
    body: "Hamstrings",
    muscles: "Hamstrings • Glutes • Low Back",
    pattern: "Hinge",
    goal: "Strength",
    equipment: "Barbell",
    level: "Intermediate",
    cue: "Keep the bar close and move from the hips, not the low back.",
  }),
  makeExercise({
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    body: "Posterior Chain",
    muscles: "Hamstrings • Glutes • Back • Core",
    pattern: "Hinge",
    goal: "Strength",
    equipment: "Barbell",
    level: "Intermediate",
    cue: "Push the floor away and keep the bar close from start to finish.",
  }),
  makeExercise({
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    body: "Posterior Chain",
    muscles: "Glutes • Hamstrings • Quads • Back",
    pattern: "Hinge",
    goal: "Strength",
    equipment: "Trap Bar",
    level: "Beginner",
    cue: "Brace hard, grip the floor with your feet, and stand tall through the hips.",
  }),
  makeExercise({
    id: "single-leg-rdl",
    name: "Single-Leg RDL",
    body: "Hamstrings",
    muscles: "Hamstrings • Glutes • Core • Hip Stabilizers",
    pattern: "Hinge",
    goal: "Stability",
    equipment: "Dumbbell",
    level: "Intermediate",
    cue: "Reach the back leg long and keep your hips square.",
  }),
  makeExercise({
    id: "hip-thrust",
    name: "Hip Thrust",
    body: "Glutes",
    muscles: "Glutes • Hamstrings • Core",
    pattern: "Hinge",
    goal: "Hypertrophy",
    equipment: "Bench",
    level: "Beginner",
    cue: "Tuck the ribs, drive through the heels, and finish with the glutes.",
  }),
  makeExercise({
    id: "glute-bridge",
    name: "Glute Bridge",
    body: "Glutes",
    muscles: "Glutes • Hamstrings • Core",
    pattern: "Hinge",
    goal: "Hypertrophy",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Keep the ribs down and squeeze the glutes at the top.",
  }),
  makeExercise({
    id: "cable-pull-through",
    name: "Cable Pull Through",
    body: "Posterior Chain",
    muscles: "Glutes • Hamstrings • Low Back",
    pattern: "Hinge",
    goal: "Hypertrophy",
    equipment: "Cable",
    level: "Beginner",
    cue: "Let the hips travel back, then snap them through with control.",
  }),

  makeExercise({
    id: "reverse-lunge",
    name: "Reverse Lunge",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Lunge",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Step back softly and drive through the front leg.",
  }),
  makeExercise({
    id: "walking-lunge",
    name: "Walking Lunge",
    body: "Legs",
    muscles: "Quads • Glutes • Hamstrings • Core",
    pattern: "Lunge",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Intermediate",
    cue: "Control each step and keep your torso tall.",
  }),
  makeExercise({
    id: "forward-lunge",
    name: "Forward Lunge",
    body: "Legs",
    muscles: "Quads • Glutes • Core",
    pattern: "Lunge",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Step with control and push back through the lead foot.",
  }),
  makeExercise({
    id: "lateral-lunge",
    name: "Lateral Lunge",
    body: "Legs",
    muscles: "Adductors • Glutes • Quads",
    pattern: "Lunge",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Sit into the hip while keeping the opposite leg long.",
  }),
  makeExercise({
    id: "curtsy-lunge",
    name: "Curtsy Lunge",
    body: "Glutes",
    muscles: "Glutes • Quads • Hip Stabilizers",
    pattern: "Lunge",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Intermediate",
    cue: "Cross behind with control and keep the front knee stable.",
  }),

  makeExercise({
    id: "plank",
    name: "Plank",
    body: "Core",
    muscles: "Abs • Obliques • Glutes • Shoulders",
    pattern: "Anti-Extension",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Push the floor away, tuck your ribs, and squeeze your glutes.",
  }),
  makeExercise({
    id: "dead-bug",
    name: "Dead Bug",
    body: "Core",
    muscles: "Abs • Hip Flexors • Deep Core",
    pattern: "Anti-Extension",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Keep your low back quiet as your opposite arm and leg move.",
  }),
  makeExercise({
    id: "stability-ball-rollout",
    name: "Stability Ball Rollout",
    body: "Core",
    muscles: "Abs • Lats • Shoulders",
    pattern: "Anti-Extension",
    goal: "Stability",
    equipment: "Stability Ball",
    level: "Intermediate",
    cue: "Reach long without letting your ribs flare.",
  }),
  makeExercise({
    id: "ab-wheel",
    name: "Ab Wheel",
    body: "Core",
    muscles: "Abs • Lats • Shoulders",
    pattern: "Anti-Extension",
    goal: "Strength",
    equipment: "Ab Wheel",
    level: "Advanced",
    cue: "Move slowly and only go as far as you can control your spine.",
  }),
  makeExercise({
    id: "pallof-press",
    name: "Pallof Press",
    body: "Core",
    muscles: "Obliques • Abs • Glutes",
    pattern: "Anti-Rotation",
    goal: "Stability",
    equipment: "Cable",
    level: "Beginner",
    cue: "Press straight out and resist the cable trying to rotate you.",
  }),
  makeExercise({
    id: "half-kneeling-pallof-press",
    name: "Half-Kneeling Pallof Press",
    body: "Core",
    muscles: "Obliques • Abs • Glutes • Hip Stabilizers",
    pattern: "Anti-Rotation",
    goal: "Stability",
    equipment: "Cable",
    level: "Beginner",
    cue: "Stay tall through the hips and press without twisting.",
  }),
  makeExercise({
    id: "cable-hold",
    name: "Cable Hold",
    body: "Core",
    muscles: "Obliques • Abs • Shoulders",
    pattern: "Anti-Rotation",
    goal: "Stability",
    equipment: "Cable",
    level: "Beginner",
    cue: "Lock in your stance and hold the handle without letting your torso turn.",
  }),
  makeExercise({
    id: "suitcase-carry",
    name: "Suitcase Carry",
    body: "Core",
    muscles: "Obliques • Grip • Traps • Glutes",
    pattern: "Anti-Lateral Flexion",
    goal: "Stability",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Walk tall and do not let the weight pull you sideways.",
  }),
  makeExercise({
    id: "single-arm-farmer-carry",
    name: "Single Arm Farmer Carry",
    body: "Core",
    muscles: "Obliques • Grip • Traps • Glutes",
    pattern: "Anti-Lateral Flexion",
    goal: "Stability",
    equipment: "Kettlebell",
    level: "Beginner",
    cue: "Keep your ribs stacked and walk like the weight is not there.",
  }),
  makeExercise({
    id: "cable-wood-chop",
    name: "Cable Wood Chop",
    body: "Core",
    muscles: "Obliques • Abs • Hips",
    pattern: "Rotation",
    goal: "Power",
    equipment: "Cable",
    level: "Intermediate",
    cue: "Rotate through the trunk and hips without yanking with the arms.",
  }),
  makeExercise({
    id: "med-ball-rotations",
    name: "Med Ball Rotations",
    body: "Core",
    muscles: "Obliques • Abs • Hips",
    pattern: "Rotation",
    goal: "Power",
    equipment: "Medicine Ball",
    level: "Intermediate",
    cue: "Turn fast, stay balanced, and own the finish.",
  }),

  makeExercise({
    id: "push-up",
    name: "Push-Up",
    body: "Chest",
    muscles: "Chest • Triceps • Shoulders • Core",
    pattern: "Horizontal Push",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Keep your ribs down, squeeze your glutes, and lower as one solid unit.",
  }),
  makeExercise({
    id: "incline-push-up",
    name: "Incline Push-Up",
    body: "Chest",
    muscles: "Chest • Triceps • Shoulders • Core",
    pattern: "Horizontal Push",
    goal: "Strength",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Use the incline to control full range without losing your plank.",
  }),
  makeExercise({
    id: "db-bench-press",
    name: "DB Bench Press",
    body: "Chest",
    muscles: "Chest • Triceps • Shoulders",
    pattern: "Horizontal Push",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Pull the shoulders back, lower with control, and press smoothly.",
  }),
  makeExercise({
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    body: "Chest",
    muscles: "Chest • Triceps • Shoulders",
    pattern: "Horizontal Push",
    goal: "Strength",
    equipment: "Barbell",
    level: "Intermediate",
    cue: "Set your upper back, touch with control, and drive the bar up.",
  }),
  makeExercise({
    id: "incline-db-press",
    name: "Incline DB Press",
    body: "Chest",
    muscles: "Upper Chest • Shoulders • Triceps",
    pattern: "Horizontal Push",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Intermediate",
    cue: "Keep your shoulders packed and press slightly up and in.",
  }),

  makeExercise({
    id: "db-shoulder-press",
    name: "DB Shoulder Press",
    body: "Shoulders",
    muscles: "Shoulders • Triceps • Core",
    pattern: "Vertical Push",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Intermediate",
    cue: "Brace your ribs down and press overhead without leaning back.",
  }),
  makeExercise({
    id: "arnold-press",
    name: "Arnold Press",
    body: "Shoulders",
    muscles: "Shoulders • Triceps",
    pattern: "Vertical Push",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Intermediate",
    cue: "Rotate smoothly and keep tension through the full press.",
  }),
  makeExercise({
    id: "landmine-press",
    name: "Landmine Press",
    body: "Shoulders",
    muscles: "Shoulders • Triceps • Core",
    pattern: "Vertical Push",
    goal: "Strength",
    equipment: "Landmine",
    level: "Beginner",
    cue: "Press forward and up while keeping your torso stable.",
  }),
  makeExercise({
    id: "barbell-overhead-press",
    name: "Barbell Overhead Press",
    body: "Shoulders",
    muscles: "Shoulders • Triceps • Core",
    pattern: "Vertical Push",
    goal: "Strength",
    equipment: "Barbell",
    level: "Intermediate",
    cue: "Squeeze the glutes, brace hard, and press the bar straight overhead.",
  }),

  makeExercise({
    id: "bent-over-row",
    name: "Bent Over Row",
    body: "Back",
    muscles: "Lats • Rhomboids • Rear Delts • Biceps",
    pattern: "Horizontal Pull",
    goal: "Strength",
    equipment: "Barbell",
    level: "Intermediate",
    cue: "Hold your hinge and pull the elbows back without shrugging.",
  }),
  makeExercise({
    id: "one-arm-db-row",
    name: "One Arm DB Row",
    body: "Back",
    muscles: "Lats • Rhomboids • Rear Delts • Biceps",
    pattern: "Horizontal Pull",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Reach long at the bottom, then pull your elbow toward your hip.",
  }),
  makeExercise({
    id: "chest-supported-row",
    name: "Chest Supported Row",
    body: "Back",
    muscles: "Lats • Rhomboids • Rear Delts • Biceps",
    pattern: "Horizontal Pull",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Keep your chest on the pad and row with your upper back.",
  }),
  makeExercise({
    id: "cable-row",
    name: "Cable Row",
    body: "Back",
    muscles: "Lats • Rhomboids • Biceps",
    pattern: "Horizontal Pull",
    goal: "Hypertrophy",
    equipment: "Cable",
    level: "Beginner",
    cue: "Sit tall, pull the handle toward your ribs, and avoid leaning back.",
  }),
  makeExercise({
    id: "lat-pulldown",
    name: "Lat Pulldown",
    body: "Back",
    muscles: "Lats • Upper Back • Biceps",
    pattern: "Vertical Pull",
    goal: "Strength",
    equipment: "Cable",
    level: "Beginner",
    cue: "Pull your elbows down toward your ribs without shrugging.",
  }),
  makeExercise({
    id: "assisted-pull-up",
    name: "Assisted Pull-Up",
    body: "Back",
    muscles: "Lats • Upper Back • Biceps • Core",
    pattern: "Vertical Pull",
    goal: "Strength",
    equipment: "Machine",
    level: "Beginner",
    cue: "Lead with the chest and pull down through the elbows.",
  }),
  makeExercise({
    id: "pull-up",
    name: "Pull-Up",
    body: "Back",
    muscles: "Lats • Upper Back • Biceps • Core",
    pattern: "Vertical Pull",
    goal: "Strength",
    equipment: "Pull-Up Bar",
    level: "Advanced",
    cue: "Start from a strong hang and pull your chest toward the bar.",
  }),
  makeExercise({
    id: "chin-up",
    name: "Chin-Up",
    body: "Back",
    muscles: "Lats • Biceps • Upper Back • Core",
    pattern: "Vertical Pull",
    goal: "Strength",
    equipment: "Pull-Up Bar",
    level: "Advanced",
    cue: "Keep your body tight and pull your elbows down and back.",
  }),

  makeExercise({
    id: "lateral-raise",
    name: "Lateral Raise",
    body: "Shoulders",
    muscles: "Side Delts • Upper Traps",
    pattern: "Isolation",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Raise out wide with control and avoid swinging.",
  }),
  makeExercise({
    id: "front-raise",
    name: "Front Raise",
    body: "Shoulders",
    muscles: "Front Delts • Upper Chest",
    pattern: "Isolation",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Lift to shoulder height while keeping the ribs down.",
  }),
  makeExercise({
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    body: "Shoulders",
    muscles: "Rear Delts • Rhomboids • Upper Back",
    pattern: "Isolation",
    goal: "Hypertrophy",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Reach wide and squeeze the back of the shoulders.",
  }),
  makeExercise({
    id: "face-pull",
    name: "Face Pull",
    body: "Shoulders",
    muscles: "Rear Delts • Rotator Cuff • Upper Back",
    pattern: "Pull",
    goal: "Stability",
    equipment: "Cable",
    level: "Beginner",
    cue: "Pull toward your face and rotate the hands back slightly.",
  }),
  makeExercise({
    id: "yt-raises",
    name: "YT Raises",
    body: "Shoulders",
    muscles: "Lower Traps • Rear Delts • Rotator Cuff",
    pattern: "Stability",
    goal: "Stability",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Move slowly and reach long without shrugging.",
  }),

  makeExercise({
    id: "frog-pump",
    name: "Frog Pump",
    body: "Glutes",
    muscles: "Glutes • Hip External Rotators",
    pattern: "Hinge",
    goal: "Hypertrophy",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Keep the soles of your feet together and squeeze hard at the top.",
  }),
  makeExercise({
    id: "cable-kickback",
    name: "Cable Kickback",
    body: "Glutes",
    muscles: "Glutes • Hamstrings",
    pattern: "Isolation",
    goal: "Hypertrophy",
    equipment: "Cable",
    level: "Beginner",
    cue: "Drive through the heel without arching your low back.",
  }),
  makeExercise({
    id: "glute-bridge-march",
    name: "Glute Bridge March",
    body: "Glutes",
    muscles: "Glutes • Hamstrings • Core",
    pattern: "Hinge",
    goal: "Hypertrophy",
    equipment: "Bodyweight",
    level: "Intermediate",
    cue: "Keep the hips level as one knee lifts at a time.",
  }),

  makeExercise({
    id: "hip-mobility-flow",
    name: "Hip Mobility Flow",
    body: "Mobility",
    muscles: "Hips • Glutes • Adductors",
    pattern: "Mobility",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Move slowly through each position and breathe into the tight spots.",
  }),
  makeExercise({
    id: "90-90-hip-rotation",
    name: "90/90 Hip Rotation",
    body: "Mobility",
    muscles: "Hips • Glutes • Hip Rotators",
    pattern: "Mobility",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Keep the torso tall and rotate from the hips, not the low back.",
  }),
  makeExercise({
    id: "thoracic-rotation",
    name: "Thoracic Rotation",
    body: "Mobility",
    muscles: "Upper Back • Shoulders • Rib Cage",
    pattern: "Mobility",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Rotate through the upper back while keeping the hips quiet.",
  }),
  makeExercise({
    id: "worlds-greatest-stretch",
    name: "World’s Greatest Stretch",
    body: "Mobility",
    muscles: "Hips • Hamstrings • Upper Back • Shoulders",
    pattern: "Mobility",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Move with control and pause where you feel the biggest restriction.",
  }),
  makeExercise({
    id: "ankle-dorsiflexion-drill",
    name: "Ankle Dorsiflexion Drill",
    body: "Mobility",
    muscles: "Calves • Ankles • Shins",
    pattern: "Mobility",
    goal: "Mobility",
    equipment: "Bodyweight",
    level: "Beginner",
    cue: "Drive the knee forward while keeping the heel down.",
  }),

  makeExercise({
    id: "box-jump",
    name: "Box Jump",
    body: "Full Body",
    muscles: "Quads • Glutes • Calves • Core",
    pattern: "Jump",
    goal: "Power",
    equipment: "Box",
    level: "Intermediate",
    cue: "Jump explosively, land quietly, and own the top position.",
  }),
  makeExercise({
    id: "broad-jump",
    name: "Broad Jump",
    body: "Full Body",
    muscles: "Glutes • Quads • Hamstrings • Calves",
    pattern: "Jump",
    goal: "Power",
    equipment: "Bodyweight",
    level: "Intermediate",
    cue: "Load the hips, explode forward, and stick the landing.",
  }),
  makeExercise({
    id: "med-ball-slam",
    name: "Med Ball Slam",
    body: "Full Body",
    muscles: "Abs • Lats • Shoulders • Hips",
    pattern: "Power",
    goal: "Power",
    equipment: "Medicine Ball",
    level: "Beginner",
    cue: "Reach tall, brace, and slam with the whole body.",
  }),
  makeExercise({
    id: "med-ball-chest-pass",
    name: "Med Ball Chest Pass",
    body: "Chest",
    muscles: "Chest • Triceps • Shoulders • Core",
    pattern: "Power Push",
    goal: "Power",
    equipment: "Medicine Ball",
    level: "Beginner",
    cue: "Push explosively from the chest and stay balanced.",
  }),
  makeExercise({
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    body: "Posterior Chain",
    muscles: "Glutes • Hamstrings • Core • Back",
    pattern: "Hinge",
    goal: "Power",
    equipment: "Kettlebell",
    level: "Intermediate",
    cue: "Hike the bell back and snap the hips through without squatting it.",
  }),

  makeExercise({
    id: "kettlebell-clean",
    name: "Kettlebell Clean",
    body: "Full Body",
    muscles: "Glutes • Hamstrings • Core • Shoulders",
    pattern: "Power",
    goal: "Power",
    equipment: "Kettlebell",
    level: "Intermediate",
    cue: "Use the hips to float the bell and catch it softly.",
  }),
  makeExercise({
    id: "db-thruster",
    name: "DB Thruster",
    body: "Full Body",
    muscles: "Quads • Glutes • Shoulders • Triceps • Core",
    pattern: "Squat To Press",
    goal: "Conditioning",
    equipment: "Dumbbell",
    level: "Intermediate",
    cue: "Drive from the squat into the press as one smooth movement.",
  }),
  makeExercise({
    id: "burpee",
    name: "Burpee",
    body: "Full Body",
    muscles: "Chest • Quads • Core • Shoulders",
    pattern: "Conditioning",
    goal: "Conditioning",
    equipment: "Bodyweight",
    level: "Intermediate",
    cue: "Move smoothly, stay braced, and keep the reps consistent.",
  }),
  makeExercise({
    id: "farmer-carry",
    name: "Farmer Carry",
    body: "Full Body",
    muscles: "Grip • Traps • Core • Glutes",
    pattern: "Carry",
    goal: "Strength",
    equipment: "Dumbbell",
    level: "Beginner",
    cue: "Walk tall with strong posture and controlled steps.",
  }),
  makeExercise({
    id: "sled-push",
    name: "Sled Push",
    body: "Full Body",
    muscles: "Quads • Glutes • Calves • Core",
    pattern: "Conditioning",
    goal: "Conditioning",
    equipment: "Sled",
    level: "Beginner",
    cue: "Lean in, drive the ground away, and keep steady pressure.",
  }),
  makeExercise({
    id: "sled-pull",
    name: "Sled Pull",
    body: "Full Body",
    muscles: "Back • Legs • Core • Grip",
    pattern: "Conditioning",
    goal: "Conditioning",
    equipment: "Sled",
    level: "Beginner",
    cue: "Keep tension through the rope and pull with rhythm.",
  }),
];

export const exerciseBodyParts = [
  "All",
  ...Array.from(
    new Set(exerciseLibrary.map((exercise) => exercise.body)),
  ).sort(),
];

export const exerciseGoals = [
  "All",
  "Strength",
  "Hypertrophy",
  "Stability",
  "Power",
  "Conditioning",
  "Mobility",
  "Recovery",
];

export const exercisePatterns = [
  "All",
  ...Array.from(
    new Set(exerciseLibrary.map((exercise) => exercise.pattern)),
  ).sort(),
];

export const exerciseEquipment = [
  "All",
  ...Array.from(
    new Set(exerciseLibrary.map((exercise) => exercise.equipment)),
  ).sort(),
];

export const exerciseLevels = [
  "All",
  ...Array.from(
    new Set(exerciseLibrary.map((exercise) => exercise.level)),
  ).sort(),
];
