import type {
  Apparatus,
  CoreMovement,
  ExerciseModifier,
  ExerciseModifierCategory,
  ExerciseModifierCategoryId,
  ExerciseModifierId,
  MovementPattern,
  MovementPatternCategoryId,
  MovementPatternId,
} from "@/types";

export const MOVEMENT_PATTERNS = [
  {
    id: "horizontal-push",
    label: "Horizontal Push",
    legacyPattern: "Push",
    description: "Pressing away from the torso in a mostly horizontal path.",
    plane: "sagittal",
  },
  {
    id: "horizontal-pull",
    label: "Horizontal Pull",
    legacyPattern: "Pull",
    description: "Pulling toward the torso in a mostly horizontal path.",
    plane: "sagittal",
  },
  {
    id: "vertical-push",
    label: "Vertical Push",
    legacyPattern: "Push",
    description: "Pressing overhead or upward against resistance.",
    plane: "sagittal",
  },
  {
    id: "vertical-pull",
    label: "Vertical Pull",
    legacyPattern: "Pull",
    description: "Pulling down or up through a vertical line of force.",
    plane: "sagittal",
  },
  {
    id: "squat",
    label: "Squat",
    legacyPattern: "Squat",
    description: "Knee-dominant lower-body flexion and extension.",
    plane: "sagittal",
  },
  {
    id: "hinge",
    label: "Hinge",
    legacyPattern: "Hinge",
    description: "Hip-dominant posterior-chain loading.",
    plane: "sagittal",
  },
  {
    id: "lunge",
    label: "Lunge",
    legacyPattern: "Lunge",
    description: "Split-stance lower-body loading with gait carryover.",
    plane: "multi-planar",
  },
  {
    id: "step-up",
    label: "Step-Up",
    legacyPattern: "Squat",
    description: "Vertical stepping movement onto or down from elevation.",
    plane: "sagittal",
  },
  {
    id: "hip-thrust-bridge",
    label: "Hip Thrust / Bridge",
    legacyPattern: "Hinge",
    description: "Horizontal hip extension with reduced spinal demand.",
    plane: "sagittal",
  },
  {
    id: "gait",
    label: "Gait",
    legacyPattern: "Carry",
    description: "Walking, stepping, marching, and locomotion patterns.",
    plane: "multi-planar",
  },
  {
    id: "knee-extension",
    label: "Knee Extension",
    legacyPattern: "Accessory",
    description: "Extending the knee against resistance.",
    plane: "sagittal",
  },
  {
    id: "knee-flexion",
    label: "Knee Flexion",
    legacyPattern: "Accessory",
    description: "Flexing the knee against resistance.",
    plane: "sagittal",
  },
  {
    id: "hip-extension",
    label: "Hip Extension",
    legacyPattern: "Hinge",
    description: "Extending the hip with glute-dominant emphasis.",
    plane: "sagittal",
  },
  {
    id: "hip-abduction",
    label: "Hip Abduction",
    legacyPattern: "Accessory",
    description: "Moving the femur away from midline.",
    plane: "frontal",
  },
  {
    id: "hip-adduction",
    label: "Hip Adduction",
    legacyPattern: "Accessory",
    description: "Moving the femur toward midline.",
    plane: "frontal",
  },
  {
    id: "hip-external-rotation",
    label: "Hip External Rotation",
    legacyPattern: "Mobility",
    description: "Rotating the femur outward for hip control and mobility.",
    plane: "transverse",
  },
  {
    id: "hip-internal-rotation",
    label: "Hip Internal Rotation",
    legacyPattern: "Mobility",
    description: "Rotating the femur inward for hip control and mobility.",
    plane: "transverse",
  },
  {
    id: "calf-raise",
    label: "Calf Raise",
    legacyPattern: "Accessory",
    description: "Plantar flexion through the ankle.",
    plane: "sagittal",
  },
  {
    id: "tibialis-raise",
    label: "Tibialis Raise",
    legacyPattern: "Accessory",
    description: "Dorsiflexion-focused ankle isolation.",
    plane: "sagittal",
  },
  {
    id: "plantarflexion",
    label: "Plantarflexion",
    legacyPattern: "Accessory",
    description: "Pressing through the forefoot to train calf output.",
    plane: "sagittal",
  },
  {
    id: "dorsiflexion",
    label: "Dorsiflexion",
    legacyPattern: "Accessory",
    description: "Lifting the foot toward the shin to train anterior lower leg.",
    plane: "sagittal",
  },
  {
    id: "chest-press",
    label: "Chest Press",
    legacyPattern: "Push",
    description: "Pressing away from the torso with chest emphasis.",
    plane: "sagittal",
  },
  {
    id: "shoulder-press",
    label: "Shoulder Press",
    legacyPattern: "Push",
    description: "Pressing overhead or upward.",
    plane: "sagittal",
  },
  {
    id: "chest-fly",
    label: "Chest Fly",
    legacyPattern: "Push",
    description: "Shoulder horizontal adduction with chest emphasis.",
    plane: "transverse",
  },
  {
    id: "lateral-raise",
    label: "Lateral Raise",
    legacyPattern: "Accessory",
    description: "Shoulder abduction isolation for lateral delts.",
    plane: "frontal",
  },
  {
    id: "row",
    label: "Row",
    legacyPattern: "Pull",
    description: "Pulling toward the torso.",
    plane: "sagittal",
  },
  {
    id: "pullover",
    label: "Pullover",
    legacyPattern: "Pull",
    description: "Shoulder extension pattern with lat emphasis.",
    plane: "sagittal",
  },
  {
    id: "reverse-fly",
    label: "Reverse Fly",
    legacyPattern: "Pull",
    description: "Shoulder horizontal abduction with rear-delt and upper-back emphasis.",
    plane: "transverse",
  },
  {
    id: "curl",
    label: "Curl",
    legacyPattern: "Accessory",
    description: "Elbow flexion for biceps and arm strength.",
    plane: "sagittal",
  },
  {
    id: "triceps-extension",
    label: "Triceps Extension",
    legacyPattern: "Accessory",
    description: "Elbow extension for triceps strength.",
    plane: "sagittal",
  },
  {
    id: "elbow-flexion",
    label: "Elbow Flexion",
    legacyPattern: "Accessory",
    description: "Flexing the elbow for biceps and arm pulling support.",
    plane: "sagittal",
  },
  {
    id: "elbow-extension",
    label: "Elbow Extension",
    legacyPattern: "Accessory",
    description: "Extending the elbow for triceps and pressing support.",
    plane: "sagittal",
  },
  {
    id: "wrist-flexion",
    label: "Wrist Flexion",
    legacyPattern: "Accessory",
    description: "Flexing the wrist against resistance.",
    plane: "sagittal",
  },
  {
    id: "wrist-extension",
    label: "Wrist Extension",
    legacyPattern: "Accessory",
    description: "Extending the wrist against resistance.",
    plane: "sagittal",
  },
  {
    id: "wrist-rotation",
    label: "Wrist Rotation",
    legacyPattern: "Accessory",
    description: "Pronation, supination, and rotational wrist control.",
    plane: "transverse",
  },
  {
    id: "shoulder-abduction",
    label: "Shoulder Abduction",
    legacyPattern: "Accessory",
    description: "Raising the arm away from the body through the frontal plane.",
    plane: "frontal",
  },
  {
    id: "shoulder-external-rotation",
    label: "Shoulder External Rotation",
    legacyPattern: "Accessory",
    description: "Rotating the upper arm outward for cuff and shoulder control.",
    plane: "transverse",
  },
  {
    id: "shoulder-internal-rotation",
    label: "Shoulder Internal Rotation",
    legacyPattern: "Accessory",
    description: "Rotating the upper arm inward for cuff and shoulder control.",
    plane: "transverse",
  },
  {
    id: "scapular-control",
    label: "Scapular Control",
    legacyPattern: "Accessory",
    description:
      "Scapular retraction, protraction, elevation, depression, or control work.",
    plane: "multi-planar",
  },
  {
    id: "scapular-retraction",
    label: "Scapular Retraction",
    legacyPattern: "Pull",
    description: "Drawing the shoulder blades together under control.",
    plane: "multi-planar",
  },
  {
    id: "scapular-protraction",
    label: "Scapular Protraction",
    legacyPattern: "Push",
    description: "Reaching or wrapping the shoulder blades around the rib cage.",
    plane: "multi-planar",
  },
  {
    id: "step-gait-jump",
    label: "Step / Gait / Jump",
    legacyPattern: "Squat",
    description: "Stepping, landing, and vertical displacement patterns.",
    plane: "multi-planar",
  },
  {
    id: "ballistic-hinge",
    label: "Ballistic Hinge",
    legacyPattern: "Hinge",
    description: "Explosive hip extension for swings, snaps, and throws.",
    plane: "sagittal",
  },
  {
    id: "ballistic-throw-slam",
    label: "Ballistic Throw / Slam",
    legacyPattern: "Power",
    description: "Whole-body throwing, slamming, and projection patterns.",
    plane: "multi-planar",
  },
  {
    id: "olympic-pull-catch",
    label: "Olympic Pull / Catch",
    legacyPattern: "Power",
    description: "Triple-extension pulls, catches, and weightlifting progressions.",
    plane: "multi-planar",
  },
  {
    id: "mobility-flow",
    label: "Mobility Flow",
    legacyPattern: "Mobility",
    description: "Multi-joint mobility sequences and transitional drills.",
    plane: "multi-planar",
  },
  {
    id: "locomotion-conditioning",
    label: "Locomotion Conditioning",
    legacyPattern: "Conditioning",
    description: "Repeated whole-body transitions used for conditioning.",
    plane: "multi-planar",
  },
  {
    id: "sled-drive",
    label: "Sled Drive",
    legacyPattern: "Conditioning",
    description: "Horizontal force production through pushing or pulling a sled.",
    plane: "sagittal",
  },
  {
    id: "rotation",
    label: "Rotation",
    legacyPattern: "Rotation",
    description: "Producing force through trunk or hip rotation.",
    plane: "transverse",
  },
  {
    id: "anti-rotation",
    label: "Anti-Rotation",
    legacyPattern: "Core",
    description: "Resisting unwanted rotation while maintaining position.",
    plane: "transverse",
  },
  {
    id: "flexion",
    label: "Flexion",
    legacyPattern: "Core",
    description: "Trunk flexion or spinal flexion control.",
    plane: "sagittal",
  },
  {
    id: "anti-extension",
    label: "Anti-Extension",
    legacyPattern: "Core",
    description: "Resisting spinal extension.",
    plane: "sagittal",
  },
  {
    id: "anti-lateral-flexion",
    label: "Anti-Lateral Flexion",
    legacyPattern: "Core",
    description: "Resisting side bending.",
    plane: "frontal",
  },
  {
    id: "carry",
    label: "Carry",
    legacyPattern: "Carry",
    description: "Loaded locomotion, grip, posture, and trunk stiffness.",
    plane: "multi-planar",
  },
  {
    id: "crawl",
    label: "Crawl",
    legacyPattern: "Conditioning",
    description: "Ground-based quadruped locomotion and coordination.",
    plane: "multi-planar",
  },
  {
    id: "jump",
    label: "Jump",
    legacyPattern: "Power",
    description: "Explosive takeoff and landing pattern.",
    plane: "sagittal",
  },
  {
    id: "sprint",
    label: "Sprint",
    legacyPattern: "Conditioning",
    description: "Rapid locomotion, acceleration, or max velocity pattern.",
    plane: "sagittal",
  },
  {
    id: "throw",
    label: "Throw",
    legacyPattern: "Power",
    description: "Explosive force projection through an implement.",
    plane: "multi-planar",
  },
  {
    id: "brace",
    label: "Brace",
    legacyPattern: "Core",
    description: "Static or dynamic trunk stiffness and anti-extension work.",
    plane: "multi-planar",
  },
  {
    id: "mobility",
    label: "Mobility",
    legacyPattern: "Mobility",
    description: "Movement quality, range, and control drills.",
    plane: "multi-planar",
  },
  {
    id: "breathing-bracing",
    label: "Breathing / Bracing",
    legacyPattern: "Mobility",
    description:
      "Breathing mechanics, trunk pressure, and coordinated bracing control.",
    plane: "multi-planar",
  },
  {
    id: "neck-flexion",
    label: "Neck Flexion",
    legacyPattern: "Accessory",
    description: "Cervical flexion isolation and control.",
    plane: "sagittal",
  },
  {
    id: "neck-extension",
    label: "Neck Extension",
    legacyPattern: "Accessory",
    description: "Cervical extension isolation and control.",
    plane: "sagittal",
  },
  {
    id: "neck-rotation",
    label: "Neck Rotation",
    legacyPattern: "Accessory",
    description: "Cervical rotation isolation and control.",
    plane: "transverse",
  },
  {
    id: "integrated-movement",
    label: "Integrated Movement",
    legacyPattern: "Conditioning",
    description: "Multi-pattern exercise combining several movement demands.",
    plane: "multi-planar",
  },
] as const satisfies readonly MovementPattern[];

export const MOVEMENT_PATTERN_CATEGORY_BY_ID = {
  "horizontal-push": "upper-push",
  "horizontal-pull": "upper-pull",
  "vertical-push": "upper-push",
  "vertical-pull": "upper-pull",
  squat: "lower-body-compound",
  hinge: "lower-body-compound",
  lunge: "lower-body-compound",
  "step-up": "lower-body-compound",
  "hip-thrust-bridge": "lower-body-compound",
  gait: "athletic",
  "knee-extension": "lower-body-isolation",
  "knee-flexion": "lower-body-isolation",
  "hip-extension": "lower-body-compound",
  "hip-abduction": "lower-body-isolation",
  "hip-adduction": "lower-body-isolation",
  "hip-external-rotation": "lower-body-isolation",
  "hip-internal-rotation": "lower-body-isolation",
  "calf-raise": "lower-body-isolation",
  "tibialis-raise": "lower-body-isolation",
  plantarflexion: "lower-body-isolation",
  dorsiflexion: "lower-body-isolation",
  "chest-press": "upper-push",
  "shoulder-press": "upper-push",
  "chest-fly": "upper-push",
  "lateral-raise": "upper-push",
  row: "upper-pull",
  pullover: "upper-pull",
  "reverse-fly": "upper-pull",
  curl: "arm-isolation",
  "triceps-extension": "arm-isolation",
  "elbow-flexion": "arm-isolation",
  "elbow-extension": "arm-isolation",
  "wrist-flexion": "arm-isolation",
  "wrist-extension": "arm-isolation",
  "wrist-rotation": "arm-isolation",
  "shoulder-abduction": "upper-push",
  "shoulder-external-rotation": "arm-isolation",
  "shoulder-internal-rotation": "arm-isolation",
  "scapular-control": "arm-isolation",
  "scapular-retraction": "upper-pull",
  "scapular-protraction": "upper-push",
  "step-gait-jump": "athletic",
  "ballistic-hinge": "athletic",
  "ballistic-throw-slam": "athletic",
  "olympic-pull-catch": "athletic",
  "mobility-flow": "mobility",
  "locomotion-conditioning": "athletic",
  "sled-drive": "athletic",
  rotation: "core",
  "anti-rotation": "core",
  flexion: "core",
  "anti-extension": "core",
  "anti-lateral-flexion": "core",
  carry: "athletic",
  crawl: "athletic",
  jump: "athletic",
  sprint: "athletic",
  throw: "athletic",
  brace: "core",
  mobility: "mobility",
  "breathing-bracing": "mobility",
  "neck-flexion": "cervical-isolation",
  "neck-extension": "cervical-isolation",
  "neck-rotation": "cervical-isolation",
  "integrated-movement": "integrated",
} as const satisfies Record<MovementPatternId, MovementPatternCategoryId>;

export const MOVEMENT_PATTERN_BY_ID = Object.fromEntries(
  MOVEMENT_PATTERNS.map((pattern) => [pattern.id, pattern]),
) as unknown as Record<MovementPatternId, MovementPattern>;

export const EXERCISE_MODIFIER_CATEGORIES = [
  {
    id: "apparatus",
    label: "Apparatus",
    description: "Primary tool or loading source used for the variation.",
    displayOrder: 10,
  },
  {
    id: "angle-position",
    label: "Angle / Position",
    description: "Bench angle, body position, or stance setup.",
    displayOrder: 20,
  },
  {
    id: "limb-usage",
    label: "Limb Usage",
    description: "How limbs share or alternate the work.",
    displayOrder: 30,
  },
  {
    id: "direction",
    label: "Direction",
    description: "Primary travel, loading path, or movement orientation.",
    displayOrder: 35,
  },
  {
    id: "stability",
    label: "Stability",
    description: "Balance demand or support surface constraint.",
    displayOrder: 40,
  },
  {
    id: "tempo",
    label: "Tempo",
    description: "Rep speed, pauses, and contraction emphasis.",
    displayOrder: 50,
  },
  {
    id: "assistance-resistance",
    label: "Assistance / Resistance",
    description: "Extra help, load, or resistance profile.",
    displayOrder: 60,
  },
  {
    id: "range-of-motion",
    label: "Range Of Motion",
    description: "Depth, endpoint, and path constraints.",
    displayOrder: 70,
  },
  {
    id: "training-intent",
    label: "Intent / Training Emphasis",
    description: "Why the variation is being prescribed.",
    displayOrder: 80,
  },
  {
    id: "load-behavior",
    label: "Load Behavior",
    description: "How force is expressed across the rep or skill.",
    displayOrder: 90,
  },
] as const satisfies readonly ExerciseModifierCategory[];

export const EXERCISE_MODIFIER_CATEGORY_BY_ID = Object.fromEntries(
  EXERCISE_MODIFIER_CATEGORIES.map((category) => [category.id, category]),
) as unknown as Record<ExerciseModifierCategoryId, ExerciseModifierCategory>;

export const APPARATUS_MODIFIERS = [
  {
    id: "apparatus:dumbbell",
    categoryId: "apparatus",
    apparatusId: "dumbbell",
    slug: "dumbbell",
    label: "Dumbbell",
    aliases: ["db", "dumbbells"],
    displayOrder: 10,
    loadingStyle: "external-load",
  },
  {
    id: "apparatus:barbell",
    categoryId: "apparatus",
    apparatusId: "barbell",
    slug: "barbell",
    label: "Barbell",
    aliases: ["bb"],
    displayOrder: 20,
    loadingStyle: "external-load",
  },
  {
    id: "apparatus:cable",
    categoryId: "apparatus",
    apparatusId: "cable",
    slug: "cable",
    label: "Cable",
    displayOrder: 30,
    loadingStyle: "machine-guided",
  },
  {
    id: "apparatus:machine",
    categoryId: "apparatus",
    apparatusId: "machine",
    slug: "machine",
    label: "Machine",
    displayOrder: 40,
    loadingStyle: "machine-guided",
  },
  {
    id: "apparatus:kettlebell",
    categoryId: "apparatus",
    apparatusId: "kettlebell",
    slug: "kettlebell",
    label: "Kettlebell",
    aliases: ["kb"],
    displayOrder: 50,
    loadingStyle: "external-load",
  },
  {
    id: "apparatus:bodyweight",
    categoryId: "apparatus",
    apparatusId: "bodyweight",
    slug: "bodyweight",
    label: "Bodyweight",
    displayOrder: 60,
    loadingStyle: "bodyweight",
  },
  {
    id: "apparatus:band",
    categoryId: "apparatus",
    apparatusId: "band",
    slug: "band",
    label: "Band",
    displayOrder: 70,
    loadingStyle: "elastic",
  },
  {
    id: "apparatus:smith-machine",
    categoryId: "apparatus",
    apparatusId: "smith-machine",
    slug: "smith-machine",
    label: "Smith Machine",
    displayOrder: 80,
    loadingStyle: "machine-guided",
  },
  {
    id: "apparatus:trap-bar",
    categoryId: "apparatus",
    apparatusId: "trap-bar",
    slug: "trap-bar",
    label: "Trap Bar",
    displayOrder: 90,
    loadingStyle: "external-load",
  },
  {
    id: "apparatus:trx",
    categoryId: "apparatus",
    apparatusId: "trx",
    slug: "trx",
    label: "TRX",
    aliases: ["suspension", "suspension trainer", "suspension training"],
    displayOrder: 100,
    loadingStyle: "suspension",
  },
  {
    id: "apparatus:suspension",
    categoryId: "apparatus",
    apparatusId: "suspension",
    slug: "suspension",
    label: "TRX",
    aliases: ["trx", "suspension trainer", "suspension training"],
    displayOrder: 101,
    loadingStyle: "suspension",
  },
  {
    id: "apparatus:landmine",
    categoryId: "apparatus",
    apparatusId: "landmine",
    slug: "landmine",
    label: "Landmine",
    displayOrder: 110,
    loadingStyle: "external-load",
  },
  {
    id: "apparatus:bench",
    categoryId: "apparatus",
    apparatusId: "bench",
    slug: "bench",
    label: "Bench",
    displayOrder: 120,
    loadingStyle: "support",
  },
  {
    id: "apparatus:box",
    categoryId: "apparatus",
    apparatusId: "box",
    slug: "box",
    label: "Box",
    displayOrder: 130,
    loadingStyle: "support",
  },
  {
    id: "apparatus:medicine-ball",
    categoryId: "apparatus",
    apparatusId: "medicine-ball",
    slug: "medicine-ball",
    label: "Medicine Ball",
    aliases: ["med ball"],
    displayOrder: 140,
    loadingStyle: "external-load",
  },
  {
    id: "apparatus:pull-up-bar",
    categoryId: "apparatus",
    apparatusId: "pull-up-bar",
    slug: "pull-up-bar",
    label: "Pull-Up Bar",
    displayOrder: 150,
    loadingStyle: "support",
  },
  {
    id: "apparatus:sled",
    categoryId: "apparatus",
    apparatusId: "sled",
    slug: "sled",
    label: "Sled",
    displayOrder: 160,
    loadingStyle: "sled",
  },
  {
    id: "apparatus:stability-ball",
    categoryId: "apparatus",
    apparatusId: "stability-ball",
    slug: "stability-ball",
    label: "Stability Ball",
    aliases: ["swiss ball"],
    displayOrder: 170,
    loadingStyle: "support",
  },
  {
    id: "apparatus:ab-wheel",
    categoryId: "apparatus",
    apparatusId: "ab-wheel",
    slug: "ab-wheel",
    label: "Ab Wheel",
    displayOrder: 180,
    loadingStyle: "support",
  },
] as const satisfies readonly Apparatus[];

export const ANGLE_POSITION_MODIFIERS = [
  ["incline", "Incline"],
  ["decline", "Decline"],
  ["flat", "Flat"],
  ["floor", "Floor"],
  ["hands-elevated", "Hands Elevated"],
  ["feet-elevated", "Feet Elevated"],
  ["seated", "Seated"],
  ["standing", "Standing"],
  ["half-kneeling", "Half-Kneeling"],
  ["split-stance", "Split-Stance"],
  ["tall-kneeling", "Tall-Kneeling"],
  ["supine", "Supine"],
  ["prone", "Prone"],
  ["lying", "Lying"],
  ["side-lying", "Side-Lying"],
  ["bent-over", "Bent Over"],
  ["chest-supported", "Chest Supported"],
  ["bench-supported", "Bench Supported"],
  ["plank", "Plank Position"],
  ["rear-foot-elevated", "Rear Foot Elevated"],
  ["front-foot-elevated", "Front Foot Elevated"],
  ["goblet", "Goblet Load"],
  ["front-loaded", "Front Loaded"],
  ["back-loaded", "Back Loaded"],
  ["overhead", "Overhead"],
  ["preacher", "Preacher Position"],
  ["side-support", "Side Support"],
  ["quadruped", "Quadruped"],
].map(([slug, label], index) => ({
  id: `angle-position:${slug}`,
  categoryId: "angle-position",
  slug,
  label,
  displayOrder: (index + 1) * 10,
})) as ExerciseModifier[];

export const LIMB_USAGE_MODIFIERS = [
  {
    id: "limb-usage:bilateral",
    categoryId: "limb-usage",
    slug: "bilateral",
    label: "Bilateral",
    includeInDisplayName: false,
    displayOrder: 10,
  },
  {
    id: "limb-usage:unilateral",
    categoryId: "limb-usage",
    slug: "unilateral",
    label: "Unilateral",
    displayPrefix: "Single-Arm",
    aliases: ["single arm", "single-leg"],
    displayOrder: 20,
  },
  {
    id: "limb-usage:alternating",
    categoryId: "limb-usage",
    slug: "alternating",
    label: "Alternating",
    displayOrder: 30,
  },
  {
    id: "limb-usage:staggered",
    categoryId: "limb-usage",
    slug: "staggered",
    label: "Staggered",
    displayOrder: 40,
  },
  {
    id: "limb-usage:offset",
    categoryId: "limb-usage",
    slug: "offset",
    label: "Offset",
    displayOrder: 50,
  },
  {
    id: "limb-usage:standard-stance",
    categoryId: "limb-usage",
    slug: "standard-stance",
    label: "Standard Stance",
    includeInDisplayName: false,
    displayOrder: 60,
  },
  {
    id: "limb-usage:conventional-stance",
    categoryId: "limb-usage",
    slug: "conventional-stance",
    label: "Conventional Stance",
    displayOrder: 70,
  },
  {
    id: "limb-usage:sumo-stance",
    categoryId: "limb-usage",
    slug: "sumo-stance",
    label: "Sumo Stance",
    aliases: ["wide stance"],
    displayOrder: 80,
  },
  {
    id: "limb-usage:wide-stance",
    categoryId: "limb-usage",
    slug: "wide-stance",
    label: "Wide Stance",
    displayOrder: 90,
  },
  {
    id: "limb-usage:close-grip",
    categoryId: "limb-usage",
    slug: "close-grip",
    label: "Close Grip",
    displayOrder: 100,
  },
  {
    id: "limb-usage:wide-grip",
    categoryId: "limb-usage",
    slug: "wide-grip",
    label: "Wide Grip",
    displayOrder: 110,
  },
  {
    id: "limb-usage:neutral-grip",
    categoryId: "limb-usage",
    slug: "neutral-grip",
    label: "Neutral Grip",
    displayOrder: 120,
  },
  {
    id: "limb-usage:overhand-grip",
    categoryId: "limb-usage",
    slug: "overhand-grip",
    label: "Overhand Grip",
    displayOrder: 130,
  },
  {
    id: "limb-usage:underhand-grip",
    categoryId: "limb-usage",
    slug: "underhand-grip",
    label: "Underhand Grip",
    displayOrder: 140,
  },
  {
    id: "limb-usage:single-arm",
    categoryId: "limb-usage",
    slug: "single-arm",
    label: "Single-Arm",
    displayOrder: 150,
  },
  {
    id: "limb-usage:single-leg",
    categoryId: "limb-usage",
    slug: "single-leg",
    label: "Single-Leg",
    displayOrder: 160,
  },
] as const satisfies readonly ExerciseModifier[];

export const DIRECTION_MODIFIERS = [
  ["vertical", "Vertical"],
  ["forward", "Forward"],
  ["reverse", "Reverse"],
  ["walking", "Walking"],
  ["lateral", "Lateral"],
  ["rotational", "Rotational"],
  ["crossover", "Crossover"],
].map(([slug, label], index) => ({
  id: `direction:${slug}`,
  categoryId: "direction",
  slug,
  label,
  displayOrder: (index + 1) * 10,
})) as ExerciseModifier[];

export const STABILITY_MODIFIERS = [
  {
    id: "stability:stable",
    categoryId: "stability",
    slug: "stable",
    label: "Stable",
    includeInDisplayName: false,
    displayOrder: 10,
  },
  ["unstable", "Unstable"],
  ["swiss-ball", "Swiss Ball"],
  ["bosu", "BOSU"],
  ["suspension", "Suspension"],
  ["single-leg", "Single-Leg"],
  ["balance-focused", "Balance-Focused"],
].map((modifier, index) =>
  Array.isArray(modifier)
    ? {
        id: `stability:${modifier[0]}`,
        categoryId: "stability",
        slug: modifier[0],
        label: modifier[1],
        displayOrder: (index + 1) * 10,
      }
    : modifier,
) as ExerciseModifier[];

export const TEMPO_MODIFIERS = [
  ["explosive", "Explosive"],
  ["paused", "Paused"],
  ["eccentric-only", "Eccentric-Only"],
  ["slow-eccentric", "Slow Eccentric"],
  ["isometric", "Isometric"],
  ["tempo-controlled", "Tempo-Controlled"],
].map(([slug, label], index) => ({
  id: `tempo:${slug}`,
  categoryId: "tempo",
  slug,
  label,
  displayOrder: (index + 1) * 10,
})) as ExerciseModifier[];

export const ASSISTANCE_RESISTANCE_MODIFIERS = [
  ["assisted", "Assisted"],
  ["band-assisted", "Band-Assisted"],
  ["weighted", "Weighted"],
  ["accommodating-resistance", "Accommodating Resistance"],
  ["deloaded", "Deloaded"],
  ["partner-assisted", "Partner-Assisted"],
].map(([slug, label], index) => ({
  id: `assistance-resistance:${slug}`,
  categoryId: "assistance-resistance",
  slug,
  label,
  displayOrder: (index + 1) * 10,
})) as ExerciseModifier[];

export const RANGE_OF_MOTION_MODIFIERS = [
  {
    id: "range-of-motion:full-rom",
    categoryId: "range-of-motion",
    slug: "full-rom",
    label: "Full ROM",
    includeInDisplayName: false,
    displayOrder: 10,
  },
  ["partial-rom", "Partial ROM"],
  ["deficit", "Deficit"],
  ["dead-stop", "Dead Stop"],
  ["pin-press", "Pin Press"],
  ["extended-rom", "Extended ROM"],
].map((modifier, index) =>
  Array.isArray(modifier)
    ? {
        id: `range-of-motion:${modifier[0]}`,
        categoryId: "range-of-motion",
        slug: modifier[0],
        label: modifier[1],
        displayOrder: (index + 1) * 10,
      }
    : modifier,
) as ExerciseModifier[];

export const TRAINING_INTENT_MODIFIERS = [
  ["hypertrophy", "Hypertrophy"],
  ["strength", "Strength"],
  ["power", "Power"],
  ["endurance", "Endurance"],
  ["rehab", "Rehab"],
  ["mobility", "Mobility"],
  ["stability", "Stability"],
  ["athletic-performance", "Athletic Performance"],
].map(([slug, label], index) => ({
  id: `training-intent:${slug}`,
  categoryId: "training-intent",
  slug,
  label,
  includeInDisplayName: false,
  displayOrder: (index + 1) * 10,
})) as ExerciseModifier[];

export const LOAD_BEHAVIOR_MODIFIERS = [
  ["constant-load", "Constant Load"],
  ["variable-resistance", "Variable Resistance"],
  ["accommodating-curve", "Accommodating Curve"],
  ["ascending-strength-curve", "Ascending Strength Curve"],
  ["descending-strength-curve", "Descending Strength Curve"],
  ["ballistic", "Ballistic"],
  ["cyclical", "Cyclical"],
  ["grind", "Grind"],
  ["loaded-carry", "Loaded Carry"],
  ["skill-complex", "Skill Complex"],
].map(([slug, label], index) => ({
  id: `load-behavior:${slug}`,
  categoryId: "load-behavior",
  slug,
  label,
  includeInDisplayName: false,
  displayOrder: (index + 1) * 10,
})) as ExerciseModifier[];

export const ALL_EXERCISE_MODIFIERS = [
  ...APPARATUS_MODIFIERS,
  ...ANGLE_POSITION_MODIFIERS,
  ...LIMB_USAGE_MODIFIERS,
  ...DIRECTION_MODIFIERS,
  ...STABILITY_MODIFIERS,
  ...TEMPO_MODIFIERS,
  ...ASSISTANCE_RESISTANCE_MODIFIERS,
  ...RANGE_OF_MOTION_MODIFIERS,
  ...TRAINING_INTENT_MODIFIERS,
  ...LOAD_BEHAVIOR_MODIFIERS,
] as const satisfies readonly ExerciseModifier[];

export const EXERCISE_MODIFIER_BY_ID = Object.fromEntries(
  ALL_EXERCISE_MODIFIERS.map((modifier) => [modifier.id, modifier]),
) as unknown as Record<ExerciseModifierId, ExerciseModifier>;

const commonModifierCategories: ExerciseModifierCategoryId[] = [
  "apparatus",
  "angle-position",
  "limb-usage",
  "direction",
  "stability",
  "tempo",
  "assistance-resistance",
  "range-of-motion",
  "training-intent",
  "load-behavior",
];

export const CORE_MOVEMENTS = [
  {
    id: "chest-press",
    label: "Chest Press",
    patternId: "horizontal-push",
    bodyRegion: "Chest",
    primaryMuscles: ["Pecs", "Triceps"],
    secondaryMuscles: ["Anterior Delts", "Core"],
    aliases: ["bench press", "press", "push-up"],
    defaultCue:
      "Brace, keep the shoulder blades controlled, and press without losing rib position.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "row",
    label: "Row",
    patternId: "horizontal-pull",
    bodyRegion: "Back",
    primaryMuscles: ["Lats", "Mid Back"],
    secondaryMuscles: ["Rear Delts", "Biceps", "Core"],
    aliases: ["db row", "cable row", "machine row"],
    defaultCue:
      "Pull from the elbow, keep the ribs stacked, and finish without shrugging.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "squat",
    label: "Squat",
    patternId: "squat",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Core", "Adductors"],
    aliases: ["goblet squat", "front squat", "back squat"],
    defaultCue:
      "Brace, sit between the hips, and keep pressure through the whole foot.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "hinge",
    label: "Hinge",
    patternId: "hinge",
    bodyRegion: "Posterior Chain",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Low Back", "Core"],
    aliases: ["deadlift", "rdl", "romanian deadlift"],
    defaultCue:
      "Push the hips back, keep the load close, and stand tall through the glutes.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "lunge",
    label: "Lunge",
    patternId: "lunge",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Stabilizers"],
    aliases: ["split squat", "reverse lunge", "walking lunge"],
    defaultCue:
      "Own the front foot, keep the torso tall, and move with control.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:staggered",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "shoulder-press",
    label: "Shoulder Press",
    patternId: "vertical-push",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Shoulders", "Triceps"],
    secondaryMuscles: ["Upper Back", "Core"],
    aliases: ["overhead press", "military press"],
    defaultCue:
      "Stack ribs over pelvis, press overhead, and avoid leaning back.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "pulldown",
    label: "Pulldown",
    patternId: "vertical-pull",
    bodyRegion: "Back",
    primaryMuscles: ["Lats", "Biceps"],
    secondaryMuscles: ["Mid Back", "Rear Delts"],
    aliases: ["lat pulldown"],
    defaultCue:
      "Drive elbows down, keep the chest proud, and avoid yanking from the neck.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:cable",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "pull-up",
    label: "Pull-Up",
    patternId: "vertical-pull",
    bodyRegion: "Back",
    primaryMuscles: ["Lats", "Biceps"],
    secondaryMuscles: ["Core", "Mid Back"],
    aliases: ["chin-up", "assisted pull-up"],
    defaultCue:
      "Start from control, pull the elbows down, and finish without craning the neck.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "carry",
    label: "Carry",
    patternId: "carry",
    bodyRegion: "Full Body",
    primaryMuscles: ["Core", "Grip"],
    secondaryMuscles: ["Traps", "Glutes", "Shoulders"],
    aliases: ["farmer carry", "suitcase carry"],
    defaultCue:
      "Walk tall, keep the ribs down, and resist leaning as you move.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "limb-usage:bilateral",
      "stability:stable",
    ],
  },
  {
    id: "rotation",
    label: "Rotation",
    patternId: "rotation",
    bodyRegion: "Core",
    primaryMuscles: ["Obliques", "Hips"],
    secondaryMuscles: ["Shoulders", "Glutes"],
    aliases: ["wood chop", "rotational throw"],
    defaultCue:
      "Rotate from the trunk and hips while keeping control through the finish.",
    defaultLevel: "beginner",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "anti-rotation",
    label: "Anti-Rotation",
    patternId: "anti-rotation",
    bodyRegion: "Core",
    primaryMuscles: ["Obliques", "Deep Core"],
    secondaryMuscles: ["Glutes", "Shoulders"],
    aliases: ["pallof press", "anti-rotation press"],
    defaultCue:
      "Press away and resist rotation without letting the ribs flare.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:cable",
      "limb-usage:bilateral",
      "stability:stable",
    ],
  },
  {
    id: "brace-plank",
    label: "Brace / Plank",
    patternId: "brace",
    bodyRegion: "Core",
    primaryMuscles: ["Deep Core", "Abs"],
    secondaryMuscles: ["Glutes", "Shoulders"],
    aliases: ["plank", "dead bug", "brace"],
    defaultCue:
      "Stack ribs over pelvis, breathe calmly, and keep tension without gripping.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
    ],
  },
  {
    id: "leg-extension",
    label: "Leg Extension",
    patternId: "knee-extension",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads"],
    secondaryMuscles: ["Hip Flexors"],
    aliases: ["machine leg extension", "knee extension"],
    defaultCue:
      "Control the pad, extend the knee fully, and avoid throwing the weight.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:ascending-strength-curve",
    ],
  },
  {
    id: "leg-curl",
    label: "Leg Curl",
    patternId: "knee-flexion",
    bodyRegion: "Hamstrings",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves"],
    aliases: ["hamstring curl", "seated leg curl", "lying leg curl"],
    defaultCue:
      "Keep the hips quiet, curl with control, and own the end range.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "hip-thrust-glute-bridge",
    label: "Hip Thrust / Glute Bridge",
    patternId: "hip-extension",
    bodyRegion: "Glutes",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    aliases: ["hip thrust", "glute bridge", "barbell hip thrust"],
    defaultCue:
      "Tuck the ribs, drive through the heels, and finish with the glutes.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:ascending-strength-curve",
    ],
  },
  {
    id: "calf-raise",
    label: "Calf Raise",
    patternId: "plantarflexion",
    bodyRegion: "Calves",
    primaryMuscles: ["Calves"],
    secondaryMuscles: ["Foot Intrinsics"],
    aliases: ["standing calf raise", "seated calf raise"],
    defaultCue:
      "Press through the big toe, pause tall, and lower with control.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "endurance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "tibialis-raise",
    label: "Tibialis Raise",
    patternId: "dorsiflexion",
    bodyRegion: "Lower Legs",
    primaryMuscles: ["Tibialis Anterior"],
    secondaryMuscles: ["Ankles"],
    aliases: ["toe raise", "shin raise", "tib raise"],
    defaultCue:
      "Lift the toes toward the shins, pause, and lower without collapsing.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "endurance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "hip-abduction",
    label: "Hip Abduction",
    patternId: "hip-abduction",
    bodyRegion: "Hips / Glutes",
    primaryMuscles: ["Glute Med", "Glute Min"],
    secondaryMuscles: ["Hip Stabilizers"],
    aliases: ["abductor machine", "banded abduction"],
    defaultCue:
      "Move from the hip, keep the pelvis steady, and avoid swinging.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:band",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "hip-adduction",
    label: "Hip Adduction",
    patternId: "hip-adduction",
    bodyRegion: "Hips / Adductors",
    primaryMuscles: ["Adductors"],
    secondaryMuscles: ["Pelvic Stabilizers"],
    aliases: ["adductor machine", "copenhagen adduction"],
    defaultCue:
      "Squeeze toward midline with control and keep the pelvis quiet.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:machine",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "hip-internal-rotation",
    label: "Hip Internal Rotation",
    patternId: "hip-internal-rotation",
    bodyRegion: "Hips",
    primaryMuscles: ["Hip Rotators"],
    secondaryMuscles: ["Glutes", "Deep Core"],
    aliases: ["hip IR", "internal hip rotation"],
    defaultCue:
      "Rotate from the hip, keep the pelvis quiet, and move through controlled range.",
    defaultLevel: "beginner",
    defaultIntentIds: ["mobility", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "hip-external-rotation",
    label: "Hip External Rotation",
    patternId: "hip-external-rotation",
    bodyRegion: "Hips / Glutes",
    primaryMuscles: ["Deep Hip Rotators", "Glutes"],
    secondaryMuscles: ["Hip Stabilizers"],
    aliases: ["hip ER", "external hip rotation", "clamshell"],
    defaultCue:
      "Turn from the hip without rolling the pelvis or borrowing from the low back.",
    defaultLevel: "beginner",
    defaultIntentIds: ["mobility", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "biceps-curl",
    label: "Biceps Curl",
    patternId: "elbow-flexion",
    bodyRegion: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    aliases: ["curl", "db curl", "barbell curl", "cable curl"],
    defaultCue:
      "Keep the upper arm quiet, curl smoothly, and lower with control.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "triceps-extension",
    label: "Triceps Extension",
    patternId: "elbow-extension",
    bodyRegion: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Shoulders"],
    aliases: ["pressdown", "skull crusher", "overhead triceps extension"],
    defaultCue:
      "Lock the upper arm in place and extend through the elbow.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:cable",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "wrist-flexion",
    label: "Wrist Flexion",
    patternId: "wrist-flexion",
    bodyRegion: "Forearms",
    primaryMuscles: ["Forearm Flexors"],
    secondaryMuscles: ["Grip"],
    aliases: ["wrist curl"],
    defaultCue:
      "Curl through the wrist with a quiet forearm and controlled lower.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "wrist-extension",
    label: "Wrist Extension",
    patternId: "wrist-extension",
    bodyRegion: "Forearms",
    primaryMuscles: ["Forearm Extensors"],
    secondaryMuscles: ["Grip"],
    aliases: ["reverse wrist curl"],
    defaultCue:
      "Lift through the wrist, pause briefly, and avoid swinging the elbow.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "wrist-rotation",
    label: "Wrist Rotation",
    patternId: "wrist-rotation",
    bodyRegion: "Forearms",
    primaryMuscles: ["Forearms"],
    secondaryMuscles: ["Grip"],
    aliases: ["pronation", "supination", "hammer rotation"],
    defaultCue:
      "Rotate with control through the forearm while the elbow stays steady.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "lateral-raise",
    label: "Lateral Raise",
    patternId: "shoulder-abduction",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: ["Upper Traps", "Core"],
    aliases: ["side raise", "db lateral raise"],
    defaultCue:
      "Lead with the elbows, keep the ribs down, and stop before shrugging.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:descending-strength-curve",
    ],
  },
  {
    id: "shoulder-internal-rotation",
    label: "Shoulder Internal Rotation",
    patternId: "shoulder-internal-rotation",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Rotator Cuff"],
    secondaryMuscles: ["Anterior Shoulder"],
    aliases: ["shoulder IR", "internal rotation"],
    defaultCue:
      "Rotate from the shoulder with the ribs stacked and the elbow quiet.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:band",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "shoulder-external-rotation",
    label: "Shoulder External Rotation",
    patternId: "shoulder-external-rotation",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Rotator Cuff"],
    secondaryMuscles: ["Rear Delts"],
    aliases: ["shoulder ER", "external rotation"],
    defaultCue:
      "Rotate outward with control and keep the shoulder blade settled.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:band",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "rear-delt-raise",
    label: "Reverse Fly",
    patternId: "scapular-retraction",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Mid Back", "Rotator Cuff"],
    aliases: ["rear delt raise", "rear delt fly"],
    defaultCue:
      "Reach wide, squeeze through the upper back, and avoid momentum.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "angle-position:prone",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:descending-strength-curve",
    ],
  },
  {
    id: "face-pull",
    label: "Face Pull",
    patternId: "scapular-retraction",
    bodyRegion: "Upper Back",
    primaryMuscles: ["Rear Delts", "Mid Traps"],
    secondaryMuscles: ["Rotator Cuff", "Biceps"],
    aliases: ["rope face pull", "band face pull"],
    defaultCue:
      "Pull toward eye level, rotate gently, and keep the ribs stacked.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:cable",
      "angle-position:standing",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "scapular-control",
    label: "Scapular Control",
    patternId: "scapular-control",
    bodyRegion: "Upper Back / Shoulders",
    primaryMuscles: ["Mid Traps", "Lower Traps", "Serratus"],
    secondaryMuscles: ["Rotator Cuff", "Rear Delts"],
    aliases: ["scapular retraction", "scapular protraction", "scap setting"],
    defaultCue:
      "Move the shoulder blade with control before adding arm motion.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "shrug",
    label: "Shrug",
    patternId: "scapular-retraction",
    bodyRegion: "Upper Back",
    primaryMuscles: ["Upper Traps"],
    secondaryMuscles: ["Grip", "Neck Stabilizers"],
    aliases: ["db shrug", "barbell shrug"],
    defaultCue:
      "Lift the shoulders straight up, pause, and lower without rolling.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "step-up",
    label: "Step-Up",
    patternId: "step-gait-jump",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Calves", "Core"],
    aliases: ["box step-up", "lateral step-up"],
    defaultCue:
      "Drive through the whole foot on the box and control the lower.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:unilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "step-down",
    label: "Step-Down",
    patternId: "step-gait-jump",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Hip Stabilizers", "Calves"],
    aliases: ["box step-down", "lateral step-down"],
    defaultCue:
      "Lower under control, keep the knee tracking, and own the bottom.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:unilateral",
      "stability:balance-focused",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "split-squat",
    label: "Split Squat",
    patternId: "lunge",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    aliases: ["rear-foot elevated split squat", "bulgarian split squat"],
    defaultCue:
      "Drop straight down, keep the front foot rooted, and drive tall.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "limb-usage:staggered",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "clean-pull",
    label: "Clean Pull",
    patternId: "olympic-pull-catch",
    bodyRegion: "Full Body",
    primaryMuscles: ["Glutes", "Hamstrings", "Traps"],
    secondaryMuscles: ["Quads", "Calves", "Core"],
    aliases: ["clean high pull", "weightlifting pull"],
    defaultCue:
      "Push through the floor, stay close, and finish tall through the hips.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:barbell",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "high-pull",
    label: "High Pull",
    patternId: "olympic-pull-catch",
    bodyRegion: "Full Body",
    primaryMuscles: ["Traps", "Shoulders", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    aliases: ["clean high pull", "snatch high pull"],
    defaultCue:
      "Extend hard, keep the load close, and let the elbows rise after the hips.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:barbell",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "kettlebell-swing",
    label: "Kettlebell Swing",
    patternId: "ballistic-hinge",
    bodyRegion: "Posterior Chain",
    primaryMuscles: ["Glutes", "Hamstrings"],
    secondaryMuscles: ["Core", "Lats", "Grip"],
    aliases: ["kb swing", "hardstyle swing"],
    defaultCue:
      "Hike the bell, snap the hips, and let the arms guide instead of lift.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "endurance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:kettlebell",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "kettlebell-clean",
    label: "Kettlebell Clean",
    patternId: "olympic-pull-catch",
    bodyRegion: "Full Body",
    primaryMuscles: ["Glutes", "Hamstrings", "Upper Back"],
    secondaryMuscles: ["Core", "Grip", "Shoulders"],
    aliases: ["kb clean", "single-arm kettlebell clean"],
    defaultCue:
      "Snap from the hips and park the bell softly in the rack.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:kettlebell",
      "limb-usage:unilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "kettlebell-snatch",
    label: "Kettlebell Snatch",
    patternId: "olympic-pull-catch",
    bodyRegion: "Full Body",
    primaryMuscles: ["Glutes", "Shoulders", "Upper Back"],
    secondaryMuscles: ["Hamstrings", "Core", "Grip"],
    aliases: ["kb snatch", "single-arm kettlebell snatch"],
    defaultCue:
      "Drive from the hips, keep the bell close, and punch through smoothly overhead.",
    defaultLevel: "advanced",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:kettlebell",
      "limb-usage:unilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "turkish-get-up",
    label: "Turkish Get-Up",
    patternId: "step-gait-jump",
    bodyRegion: "Full Body",
    primaryMuscles: ["Shoulders", "Core", "Glutes"],
    secondaryMuscles: ["Hips", "Grip", "Upper Back"],
    aliases: ["tgu", "get-up"],
    defaultCue:
      "Move one position at a time and keep the loaded shoulder packed.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["stability", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:kettlebell",
      "limb-usage:unilateral",
      "stability:balance-focused",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "kettlebell-halo",
    label: "Kettlebell Halo",
    patternId: "rotation",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Shoulders", "Upper Back"],
    secondaryMuscles: ["Core", "Rotator Cuff"],
    aliases: ["kb halo", "halo"],
    defaultCue:
      "Circle the bell around the head while keeping the ribs down and neck relaxed.",
    defaultLevel: "beginner",
    defaultIntentIds: ["mobility", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:kettlebell",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "bottoms-up-press",
    label: "Bottoms-Up Press",
    patternId: "vertical-push",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Shoulders", "Triceps"],
    secondaryMuscles: ["Grip", "Rotator Cuff", "Core"],
    aliases: ["bottoms up press", "bottoms-up kettlebell press"],
    defaultCue:
      "Grip the handle hard, stack the wrist, and press only as far as you can control.",
    defaultLevel: "advanced",
    defaultIntentIds: ["stability", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:kettlebell",
      "limb-usage:unilateral",
      "stability:balance-focused",
      "range-of-motion:full-rom",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "mobility-flow",
    label: "Mobility Flow",
    patternId: "mobility-flow",
    bodyRegion: "Mobility",
    primaryMuscles: ["Hips", "Upper Back"],
    secondaryMuscles: ["Hamstrings", "Adductors", "Shoulders"],
    aliases: [
      "world's greatest stretch",
      "worlds greatest stretch",
      "hip mobility flow",
      "90/90 hip rotation",
      "mobility drill",
    ],
    defaultCue:
      "Move slowly through each position and breathe into the restriction.",
    defaultLevel: "beginner",
    defaultIntentIds: ["mobility", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "breathing-bracing",
    label: "Breathing / Bracing",
    patternId: "breathing-bracing",
    bodyRegion: "Core / Mobility",
    primaryMuscles: ["Diaphragm", "Deep Core"],
    secondaryMuscles: ["Obliques", "Low Back"],
    aliases: ["bracing", "breathing drill", "core brace"],
    defaultCue:
      "Breathe into the brace, keep the ribs stacked, and maintain quiet pressure.",
    defaultLevel: "beginner",
    defaultIntentIds: ["mobility", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "neck-flexion",
    label: "Neck Flexion",
    patternId: "neck-flexion",
    bodyRegion: "Neck",
    primaryMuscles: ["Deep Neck Flexors"],
    secondaryMuscles: ["Anterior Neck"],
    aliases: ["cervical flexion"],
    defaultCue:
      "Move slowly through the neck without jutting the chin or holding breath.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "neck-extension",
    label: "Neck Extension",
    patternId: "neck-extension",
    bodyRegion: "Neck",
    primaryMuscles: ["Cervical Extensors"],
    secondaryMuscles: ["Upper Traps"],
    aliases: ["cervical extension"],
    defaultCue:
      "Extend gently with control and keep the jaw relaxed.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "neck-rotation",
    label: "Neck Rotation",
    patternId: "neck-rotation",
    bodyRegion: "Neck",
    primaryMuscles: ["Cervical Rotators"],
    secondaryMuscles: ["Upper Traps"],
    aliases: ["cervical rotation"],
    defaultCue:
      "Rotate through comfortable range without shrugging or forcing end range.",
    defaultLevel: "beginner",
    defaultIntentIds: ["rehab", "mobility"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "jump-landing",
    label: "Jump / Landing",
    patternId: "step-gait-jump",
    bodyRegion: "Full Body",
    primaryMuscles: ["Quads", "Glutes", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core"],
    aliases: ["box jump", "broad jump", "jump", "landing"],
    defaultCue:
      "Load the hips, jump explosively, and land quietly with control.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "medicine-ball-slam",
    label: "Medicine Ball Slam",
    patternId: "ballistic-throw-slam",
    bodyRegion: "Full Body",
    primaryMuscles: ["Abs", "Lats", "Shoulders"],
    secondaryMuscles: ["Hips", "Glutes", "Core"],
    aliases: ["med ball slam", "slam"],
    defaultCue:
      "Reach tall, brace hard, and slam with the whole body.",
    defaultLevel: "beginner",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:medicine-ball",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "burpee",
    label: "Burpee",
    patternId: "locomotion-conditioning",
    bodyRegion: "Full Body",
    primaryMuscles: ["Chest", "Quads", "Core"],
    secondaryMuscles: ["Shoulders", "Glutes", "Calves"],
    aliases: ["burpee", "squat thrust"],
    defaultCue:
      "Move smoothly from the floor to standing while staying braced.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["endurance", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:cyclical",
    ],
  },
  {
    id: "sled-drive",
    label: "Sled Drive",
    patternId: "sled-drive",
    bodyRegion: "Full Body",
    primaryMuscles: ["Quads", "Glutes", "Calves"],
    secondaryMuscles: ["Core", "Back", "Grip"],
    aliases: ["sled push", "sled pull", "sled drag"],
    defaultCue:
      "Keep steady pressure into the ground and drive with rhythm.",
    defaultLevel: "beginner",
    defaultIntentIds: ["endurance", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:sled",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:cyclical",
    ],
  },
  {
    id: "chest-fly",
    label: "Chest Fly",
    patternId: "chest-fly",
    bodyRegion: "Chest",
    primaryMuscles: ["Pecs"],
    secondaryMuscles: ["Anterior Delts"],
    aliases: ["pec fly", "dumbbell fly", "cable fly"],
    defaultCue:
      "Open with control, keep a soft elbow, and bring the arms together without shrugging.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "angle-position:flat",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:descending-strength-curve",
    ],
  },
  {
    id: "vertical-pull",
    label: "Vertical Pull",
    patternId: "vertical-pull",
    bodyRegion: "Back",
    primaryMuscles: ["Lats", "Upper Back"],
    secondaryMuscles: ["Biceps", "Core"],
    aliases: ["pull-up", "chin-up", "lat pulldown"],
    defaultCue:
      "Drive the elbows down and keep the ribs stacked through the pull.",
    defaultLevel: "beginner",
    defaultIntentIds: ["strength", "hypertrophy"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "pullover",
    label: "Pullover",
    patternId: "pullover",
    bodyRegion: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Chest", "Triceps", "Core"],
    aliases: ["dumbbell pullover", "straight arm pulldown"],
    defaultCue:
      "Reach long, keep the ribs down, and pull through the lats without arching.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "mobility"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "angle-position:supine",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "reverse-fly",
    label: "Reverse Fly",
    patternId: "reverse-fly",
    bodyRegion: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Mid Back", "Rotator Cuff"],
    aliases: ["rear delt fly", "reverse dumbbell fly"],
    defaultCue:
      "Reach wide, move from the rear delts, and keep the neck relaxed.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "angle-position:prone",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "curl",
    label: "Curl",
    patternId: "curl",
    bodyRegion: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    aliases: ["biceps curl", "hammer curl", "preacher curl"],
    defaultCue:
      "Keep the upper arm quiet, curl smoothly, and lower under control.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "knee-extension",
    label: "Knee Extension",
    patternId: "knee-extension",
    bodyRegion: "Legs",
    primaryMuscles: ["Quads"],
    secondaryMuscles: ["Hip Flexors"],
    aliases: ["leg extension", "terminal knee extension"],
    defaultCue:
      "Extend the knee with control and avoid throwing the weight.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:ascending-strength-curve",
    ],
  },
  {
    id: "knee-flexion",
    label: "Knee Flexion",
    patternId: "knee-flexion",
    bodyRegion: "Hamstrings",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves"],
    aliases: ["leg curl", "hamstring curl", "nordic curl"],
    defaultCue:
      "Curl with control, keep the hips quiet, and own the end range.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:machine",
      "angle-position:seated",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:constant-load",
    ],
  },
  {
    id: "hip-thrust-bridge",
    label: "Hip Thrust / Bridge",
    patternId: "hip-thrust-bridge",
    bodyRegion: "Glutes",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    aliases: ["hip thrust", "glute bridge"],
    defaultCue:
      "Drive through the heels, keep the ribs tucked, and finish with the glutes.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "angle-position:supine",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
      "load-behavior:ascending-strength-curve",
    ],
  },
  {
    id: "flexion",
    label: "Flexion",
    patternId: "flexion",
    bodyRegion: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: ["Hip Flexors"],
    aliases: ["crunch", "sit-up", "reverse crunch"],
    defaultCue:
      "Curl with control and keep the movement coming from the trunk.",
    defaultLevel: "beginner",
    defaultIntentIds: ["hypertrophy", "stability"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "angle-position:supine",
      "limb-usage:bilateral",
      "stability:stable",
      "range-of-motion:full-rom",
    ],
  },
  {
    id: "anti-extension",
    label: "Anti-Extension",
    patternId: "anti-extension",
    bodyRegion: "Core",
    primaryMuscles: ["Deep Core", "Abs"],
    secondaryMuscles: ["Glutes", "Shoulders"],
    aliases: ["plank", "dead bug", "ab wheel rollout"],
    defaultCue:
      "Keep the ribs stacked and resist letting the low back arch.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "anti-lateral-flexion",
    label: "Anti-Lateral Flexion",
    patternId: "anti-lateral-flexion",
    bodyRegion: "Core",
    primaryMuscles: ["Obliques", "Deep Core"],
    secondaryMuscles: ["Grip", "Traps", "Glutes"],
    aliases: ["side plank", "suitcase carry", "offset hold"],
    defaultCue:
      "Stay tall and resist side bending while breathing behind the brace.",
    defaultLevel: "beginner",
    defaultIntentIds: ["stability", "strength"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:dumbbell",
      "limb-usage:offset",
      "stability:stable",
      "load-behavior:loaded-carry",
    ],
  },
  {
    id: "crawl",
    label: "Crawl",
    patternId: "crawl",
    bodyRegion: "Full Body",
    primaryMuscles: ["Core", "Shoulders"],
    secondaryMuscles: ["Quads", "Glutes"],
    aliases: ["bear crawl", "leopard crawl", "lateral crawl"],
    defaultCue:
      "Keep the hips quiet, push the floor away, and move with steady rhythm.",
    defaultLevel: "beginner",
    defaultIntentIds: ["endurance", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:cyclical",
    ],
  },
  {
    id: "jump",
    label: "Jump",
    patternId: "jump",
    bodyRegion: "Full Body",
    primaryMuscles: ["Quads", "Glutes", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core"],
    aliases: ["box jump", "broad jump", "hop"],
    defaultCue:
      "Load quietly, jump with intent, and land with control.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "sprint",
    label: "Sprint",
    patternId: "sprint",
    bodyRegion: "Full Body",
    primaryMuscles: ["Glutes", "Hamstrings", "Calves"],
    secondaryMuscles: ["Core", "Hip Flexors"],
    aliases: ["hill sprint", "sled sprint", "shuttle sprint"],
    defaultCue:
      "Attack the ground, stay tall, and keep the rhythm sharp.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:cyclical",
    ],
  },
  {
    id: "throw",
    label: "Throw",
    patternId: "throw",
    bodyRegion: "Full Body",
    primaryMuscles: ["Core", "Shoulders", "Chest"],
    secondaryMuscles: ["Glutes", "Lats"],
    aliases: ["med ball throw", "rotational throw", "slam"],
    defaultCue:
      "Brace, project force through the whole body, and finish balanced.",
    defaultLevel: "beginner",
    defaultIntentIds: ["power", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:medicine-ball",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:ballistic",
    ],
  },
  {
    id: "mobility",
    label: "Mobility",
    patternId: "mobility",
    bodyRegion: "Mobility",
    primaryMuscles: ["Hips", "Upper Back"],
    secondaryMuscles: ["Shoulders", "Ankles"],
    aliases: ["mobility drill", "range of motion", "mobility flow"],
    defaultCue:
      "Move slowly, own the range, and breathe into restriction.",
    defaultLevel: "beginner",
    defaultIntentIds: ["mobility", "rehab"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
  },
  {
    id: "integrated-movement",
    label: "Integrated Movement",
    patternId: "integrated-movement",
    bodyRegion: "Full Body",
    primaryMuscles: ["Core", "Glutes", "Shoulders"],
    secondaryMuscles: ["Chest", "Quads", "Back"],
    aliases: ["complex", "combo", "flow"],
    defaultCue:
      "Move through each pattern with control and keep transitions smooth.",
    defaultLevel: "intermediate",
    defaultIntentIds: ["endurance", "athletic-performance"],
    compatibleModifierCategoryIds: commonModifierCategories,
    defaultModifierIds: [
      "apparatus:bodyweight",
      "limb-usage:bilateral",
      "stability:stable",
      "load-behavior:skill-complex",
    ],
  },
] as const satisfies readonly CoreMovement[];

export const CORE_MOVEMENT_BY_ID = Object.fromEntries(
  CORE_MOVEMENTS.map((movement) => [movement.id, movement]),
) as unknown as Record<CoreMovement["id"], CoreMovement>;

export const getModifier = (id: ExerciseModifierId) =>
  EXERCISE_MODIFIER_BY_ID[id];

export const getModifiersByCategory = (categoryId: ExerciseModifierCategoryId) =>
  ALL_EXERCISE_MODIFIERS.filter(
    (modifier) => modifier.categoryId === categoryId,
  );
